interface Emoji {
  emoji: string;
  name: string;
}

interface EmojiCategory {
  name: string;
  emojis: Emoji[];
}

export const emojiData: EmojiCategory[] = [
  {
    name: 'Smileys & Emotion',
    emojis: [
      { emoji: '😀', name: 'grinning face' },
      { emoji: '😃', name: 'grinning face with big eyes' },
      { emoji: '😄', name: 'grinning face with smiling eyes' },
      { emoji: '😁', name: 'beaming face with smiling eyes' },
      { emoji: '😆', name: 'grinning squinting face' },
      { emoji: '😅', name: 'grinning face with sweat' },
      { emoji: '😂', name: 'face with tears of joy' },
      { emoji: '🤣', name: 'rolling on the floor laughing' },
      { emoji: '😊', name: 'smiling face with smiling eyes' },
      { emoji: '😇', name: 'smiling face with halo' },
      { emoji: '🙂', name: 'slightly smiling face' },
      { emoji: '🙃', name: 'upside-down face' },
      { emoji: '😉', name: 'winking face' },
      { emoji: '😌', name: 'relieved face' },
      { emoji: '😍', name: 'smiling face with heart-eyes' },
      { emoji: '🥰', name: 'smiling face with hearts' },
      { emoji: '😘', name: 'face blowing a kiss' },
      { emoji: '😗', name: 'kissing face' },
      { emoji: '😙', name: 'kissing face with smiling eyes' },
      { emoji: '😚', name: 'kissing face with closed eyes' },
      { emoji: '😋', name: 'face savoring food' },
      { emoji: '😛', name: 'face with tongue' },
      { emoji: '😝', name: 'squinting face with tongue' },
      { emoji: '😜', name: 'winking face with tongue' },
      { emoji: '🤪', name: 'zany face' },
      { emoji: '🤨', name: 'face with raised eyebrow' },
      { emoji: '🧐', name: 'face with monocle' },
      { emoji: '🤓', name: 'nerd face' },
      { emoji: '😎', name: 'smiling face with sunglasses' },
      { emoji: '🥸', name: 'disguised face' },
      { emoji: '🤩', name: 'star-struck' },
      { emoji: '🥳', name: 'partying face' },
      { emoji: '😏', name: 'smirking face' },
      { emoji: '😒', name: 'unamused face' },
      { emoji: '😞', name: 'disappointed face' },
      { emoji: '😔', name: 'pensive face' },
      { emoji: '😟', name: 'worried face' },
      { emoji: '😕', name: 'confused face' },
      { emoji: '🙁', name: 'slightly frowning face' },
      { emoji: '☹️', name: 'frowning face' },
      { emoji: '😣', name: 'persevering face' },
      { emoji: '😖', name: 'confounded face' },
      { emoji: '😫', name: 'tired face' },
      { emoji: '😩', name: 'weary face' },
      { emoji: '🥺', name: 'pleading face' },
      { emoji: '😢', name: 'crying face' },
      { emoji: '😭', name: 'loudly crying face' },
      { emoji: '😤', name: 'face with steam from nose' },
      { emoji: '😠', name: 'angry face' },
      { emoji: '😡', name: 'pouting face' },
      { emoji: '🤬', name: 'face with symbols on mouth' },
      { emoji: '🤯', name: 'exploding head' },
      { emoji: '😳', name: 'flushed face' },
      { emoji: '🥵', name: 'hot face' },
      { emoji: '🥶', name: 'cold face' },
      { emoji: '😱', name: 'face screaming in fear' },
      { emoji: '😨', name: 'fearful face' },
      { emoji: '😰', name: 'anxious face with sweat' },
      { emoji: '😥', name: 'sad but relieved face' },
      { emoji: '😓', name: 'downcast face with sweat' },
      { emoji: '🤗', name: 'hugging face' },
      { emoji: '🤔', name: 'thinking face' },
      { emoji: '🤭', name: 'face with hand over mouth' },
      { emoji: '🤫', name: 'shushing face' },
      { emoji: '🤥', name: 'lying face' },
      { emoji: '😶', name: 'face without mouth' },
      { emoji: '😐', name: 'neutral face' },
      { emoji: '😑', name: 'expressionless face' },
      { emoji: '😬', name: 'grimacing face' },
      { emoji: '🙄', name: 'face with rolling eyes' },
      { emoji: '😯', name: 'hushed face' },
      { emoji: '😦', name: 'frowning face with open mouth' },
      { emoji: '😧', name: 'anguished face' },
      { emoji: '😮', name: 'face with open mouth' },
      { emoji: '😲', name: 'astonished face' },
      { emoji: '🥱', name: 'yawning face' },
      { emoji: '😴', name: 'sleeping face' },
      { emoji: '🤤', name: 'drooling face' },
      { emoji: '😪', name: 'sleepy face' },
      { emoji: '😵', name: 'dizzy face' },
      { emoji: '🤐', name: 'zipper-mouth face' },
      { emoji: '🥴', name: 'woozy face' },
      { emoji: '🤢', name: 'nauseated face' },
      { emoji: '🤮', name: 'face vomiting' },
      { emoji: '🤧', name: 'sneezing face' },
      { emoji: '😷', name: 'face with medical mask' },
      { emoji: '🤒', name: 'face with thermometer' },
      { emoji: '🤕', name: 'face with head-bandage' },
      { emoji: '🤑', name: 'money-mouth face' },
      { emoji: '🤠', name: 'cowboy hat face' },
      { emoji: '😈', name: 'smiling face with horns' },
      { emoji: '👿', name: 'angry face with horns' },
      { emoji: '👹', name: 'ogre' },
      { emoji: '👺', name: 'goblin' },
      { emoji: '🤡', name: 'clown face' },
      { emoji: '💩', name: 'pile of poo' },
      { emoji: '👻', name: 'ghost' },
      { emoji: '💀', name: 'skull' },
      { emoji: '☠️', name: 'skull and crossbones' },
      { emoji: '👽', name: 'alien' },
      { emoji: '👾', name: 'alien monster' },
      { emoji: '🤖', name: 'robot' },
      { emoji: '🎃', name: 'jack-o-lantern' },
      { emoji: '😺', name: 'grinning cat' },
      { emoji: '😸', name: 'grinning cat with smiling eyes' },
      { emoji: '😹', name: 'cat with tears of joy' },
      { emoji: '😻', name: 'smiling cat with heart-eyes' },
      { emoji: '😼', name: 'cat with wry smile' },
      { emoji: '😽', name: 'kissing cat' },
      { emoji: '🙀', name: 'weary cat' },
      { emoji: '😿', name: 'crying cat' },
      { emoji: '😾', name: 'pouting cat' },
    ],
  },
  {
    name: 'People & Body',
    emojis: [
        { emoji: '👋', name: 'waving hand' },
        { emoji: '🤚', name: 'raised back of hand' },
        { emoji: '🖐', name: 'hand with fingers splayed' },
        { emoji: '✋', name: 'raised hand' },
        { emoji: '🖖', name: 'vulcan salute' },
        { emoji: '👌', name: 'ok hand' },
        { emoji: '🤌', name: 'pinched fingers' },
        { emoji: '🤏', name: 'pinching hand' },
        { emoji: '✌️', name: 'victory hand' },
        { emoji: '🤞', name: 'crossed fingers' },
        { emoji: '🤟', name: 'love-you gesture' },
        { emoji: '🤘', name: 'sign of the horns' },
        { emoji: '🤙', name: 'call me hand' },
        { emoji: '👈', name: 'backhand index pointing left' },
        { emoji: '👉', name: 'backhand index pointing right' },
        { emoji: '👆', name: 'backhand index pointing up' },
        { emoji: '🖕', name: 'middle finger' },
        { emoji: '👇', name: 'backhand index pointing down' },
        { emoji: '☝️', name: 'index pointing up' },
        { emoji: '👍', name: 'thumbs up' },
        { emoji: '👎', name: 'thumbs down' },
        { emoji: '✊', name: 'raised fist' },
        { emoji: '👊', name: 'oncoming fist' },
        { emoji: '🤛', name: 'left-facing fist' },
        { emoji: '🤜', name: 'right-facing fist' },
        { emoji: '👏', name: 'clapping hands' },
        { emoji: '🙌', name: 'raising hands' },
        { emoji: '👐', name: 'open hands' },
        { emoji: '🤲', name: 'palms up together' },
        { emoji: '🤝', name: 'handshake' },
        { emoji: '🙏', name: 'folded hands' },
        { emoji: '✍️', name: 'writing hand' },
        { emoji: '💅', name: 'nail polish' },
        { emoji: '🤳', name: 'selfie' },
        { emoji: '💪', name: 'flexed biceps' },
        { emoji: '🦾', name: 'mechanical arm' },
        { emoji: '🦵', name: 'leg' },
        { emoji: '🦿', name: 'mechanical leg' },
        { emoji: '🦶', name: 'foot' },
        { emoji: '👂', name: 'ear' },
        { emoji: '🦻', name: 'ear with hearing aid' },
        { emoji: '👃', name: 'nose' },
        { emoji: '🧠', name: 'brain' },
        { emoji: '🦷', name: 'tooth' },
        { emoji: '🦴', name: 'bone' },
        { emoji: '👀', name: 'eyes' },
        { emoji: '👁', name: 'eye' },
        { emoji: '👅', name: 'tongue' },
        { emoji: '👄', name: 'mouth' },
        { emoji: '👶', name: 'baby' },
        { emoji: '🧒', name: 'child' },
        { emoji: '👦', name: 'boy' },
        { emoji: '👧', name: 'girl' },
        { emoji: '🧑', name: 'person' },
        { emoji: '👱', name: 'person: blond hair' },
        { emoji: '👨', name: 'man' },
        { emoji: '🧔', name: 'person: beard' },
        { emoji: '👩', name: 'woman' },
        { emoji: '🧓', name: 'older person' },
        { emoji: '👴', name: 'old man' },
        { emoji: '👵', name: 'old woman' },
        { emoji: '🙍', name: 'person frowning' },
        { emoji: '🙎', name: 'person pouting' },
        { emoji: '🙅', name: 'person gesturing no' },
        { emoji: '🙆', name: 'person gesturing ok' },
        { emoji: '💁', name: 'person tipping hand' },
        { emoji: '🙋', name: 'person raising hand' },
        { emoji: '🙇', name: 'person bowing' },
        { emoji: '🤦', name: 'person facepalming' },
        { emoji: '🤷', name: 'person shrugging' },
    ]
  },
  {
    name: 'Animals & Nature',
    emojis: [
      { emoji: '🐵', name: 'monkey face' },
      { emoji: '🐒', name: 'monkey' },
      { emoji: '🦍', name: 'gorilla' },
      { emoji: '🦧', name: 'orangutan' },
      { emoji: '🐶', name: 'dog face' },
      { emoji: '🐕', name: 'dog' },
      { emoji: '🦮', name: 'guide dog' },
      { emoji: '🐕‍🦺', name: 'service dog' },
      { emoji: '🐩', name: 'poodle' },
      { emoji: '🐺', name: 'wolf' },
      { emoji: '🦊', name: 'fox' },
      { emoji: '🦝', name: 'raccoon' },
      { emoji: '🐱', name: 'cat face' },
      { emoji: '🐈', name: 'cat' },
      { emoji: '🦁', name: 'lion' },
      { emoji: '🐯', name: 'tiger face' },
      { emoji: '🐅', name: 'tiger' },
      { emoji: '🐆', name: 'leopard' },
      { emoji: '🐴', name: 'horse face' },
      { emoji: '🐎', name: 'horse' },
      { emoji: '🦄', name: 'unicorn' },
      { emoji: '🦓', name: 'zebra' },
      { emoji: '🦌', name: 'deer' },
      { emoji: '🦬', name: 'bison' },
      { emoji: '🐮', name: 'cow face' },
      { emoji: '🐂', name: 'ox' },
      { emoji: '🐃', name: 'water buffalo' },
      { emoji: '🐄', name: 'cow' },
      { emoji: '🐷', name: 'pig face' },
      { emoji: '🐖', name: 'pig' },
      { emoji: '🐗', name: 'boar' },
      { emoji: '🐽', name: 'pig nose' },
      { emoji: '🐏', name: 'ram' },
      { emoji: '🐑', name: 'ewe' },
      { emoji: '🐐', name: 'goat' },
      { emoji: '🐪', name: 'camel' },
      { emoji: '🐫', name: 'two-hump camel' },
      { emoji: '🦙', name: 'llama' },
      { emoji: '🦒', name: 'giraffe' },
      { emoji: '🐘', name: 'elephant' },
      { emoji: '🦣', name: 'mammoth' },
      { emoji: '🦏', name: 'rhinoceros' },
      { emoji: '🦛', name: 'hippopotamus' },
      { emoji: '🐭', name: 'mouse face' },
      { emoji: '🐁', name: 'mouse' },
      { emoji: '🐀', name: 'rat' },
      { emoji: '🐹', name: 'hamster' },
      { emoji: '🐰', name: 'rabbit face' },
      { emoji: '🐇', name: 'rabbit' },
      { emoji: '🐿', name: 'chipmunk' },
      { emoji: '🦫', name: 'beaver' },
      { emoji: '🦔', name: 'hedgehog' },
      { emoji: '🦇', name: 'bat' },
      { emoji: '🐻', name: 'bear' },
      { emoji: '🐼', name: 'panda' },
      { emoji: '🦥', name: 'sloth' },
      { emoji: '🦦', name: 'otter' },
      { emoji: '🦨', name: 'skunk' },
      { emoji: '🦘', name: 'kangaroo' },
      { emoji: '🦡', name: 'badger' },
      { emoji: '🐾', name: 'paw prints' },
      { emoji: '🦃', name: 'turkey' },
      { emoji: '🐔', name: 'chicken' },
      { emoji: '🐓', name: 'rooster' },
      { emoji: '🐣', name: 'hatching chick' },
      { emoji: '🐤', name: 'baby chick' },
      { emoji: '🐥', name: 'front-facing baby chick' },
      { emoji: '🐦', name: 'bird' },
      { emoji: '🐧', name: 'penguin' },
      { emoji: '🕊', name: 'dove' },
      { emoji: '🦅', name: 'eagle' },
      { emoji: '🦆', name: 'duck' },
      { emoji: '🦢', name: 'swan' },
      { emoji: '🦉', name: 'owl' },
      { emoji: '🦤', name: 'dodo' },
      { emoji: '🪶', name: 'feather' },
      { emoji: '🐸', name: 'frog' },
      { emoji: '🐊', name: 'crocodile' },
      { emoji: '🐢', name: 'turtle' },
      { emoji: '🦎', name: 'lizard' },
      { emoji: '🐍', name: 'snake' },
      { emoji: '🐲', name: 'dragon face' },
      { emoji: '🐉', name: 'dragon' },
      { emoji: '🦕', name: 'sauropod' },
      { emoji: '🦖', name: 't-rex' },
      { emoji: '🐳', name: 'spouting whale' },
      { emoji: '🐋', name: 'whale' },
      { emoji: '🐬', name: 'dolphin' },
      { emoji: '🦭', name: 'seal' },
      { emoji: '🐟', name: 'fish' },
      { emoji: '🐠', name: 'tropical fish' },
      { emoji: '🐡', name: 'blowfish' },
      { emoji: '🦈', name: 'shark' },
      { emoji: '🐙', name: 'octopus' },
      { emoji: '🐚', name: 'spiral shell' },
      { emoji: '🐌', name: 'snail' },
      { emoji: '🦋', name: 'butterfly' },
      { emoji: '🐛', name: 'bug' },
      { emoji: '🐜', name: 'ant' },
      { emoji: '🐝', name: 'honeybee' },
      { emoji: '🪲', name: 'beetle' },
      { emoji: '🐞', name: 'lady beetle' },
      { emoji: '🦗', name: 'cricket' },
      { emoji: '🪳', name: 'cockroach' },
      { emoji: '🕷', name: 'spider' },
      { emoji: '🕸', name: 'spider web' },
      { emoji: '🦂', name: 'scorpion' },
      { emoji: '🦟', name: 'mosquito' },
      { emoji: '🪰', name: 'fly' },
      { emoji: '🪱', name: 'worm' },
      { emoji: '🦠', name: 'microbe' },
      { emoji: '💐', name: 'bouquet' },
      { emoji: '🌸', name: 'cherry blossom' },
      { emoji: '💮', name: 'white flower' },
      { emoji: '🏵', name: 'rosette' },
      { emoji: '🌹', name: 'rose' },
      { emoji: '🥀', name: 'wilted flower' },
      { emoji: '🌺', name: 'hibiscus' },
      { emoji: '🌻', name: 'sunflower' },
      { emoji: '🌼', name: 'blossom' },
      { emoji: '🌷', name: 'tulip' },
      { emoji: '🌱', name: 'seedling' },
      { emoji: '🪴', name: 'potted plant' },
      { emoji: '🌲', name: 'evergreen tree' },
      { emoji: '🌳', name: 'deciduous tree' },
      { emoji: '🌴', name: 'palm tree' },
      { emoji: '🌵', name: 'cactus' },
      { emoji: '🌾', name: 'sheaf of rice' },
      { emoji: '🌿', name: 'herb' },
      { emoji: '☘️', name: 'shamrock' },
      { emoji: '🍀', name: 'four leaf clover' },
      { emoji: '🍁', name: 'maple leaf' },
      { emoji: '🍂', name: 'fallen leaf' },
      { emoji: '🍃', name: 'leaf fluttering in wind' },
    ],
  },
  {
    name: 'Food & Drink',
    emojis: [
      { emoji: '🍇', name: 'grapes' },
      { emoji: '🍈', name: 'melon' },
      { emoji: '🍉', name: 'watermelon' },
      { emoji: '🍊', name: 'tangerine' },
      { emoji: '🍋', name: 'lemon' },
      { emoji: '🍌', name: 'banana' },
      { emoji: '🍍', name: 'pineapple' },
      { emoji: '🥭', name: 'mango' },
      { emoji: '🍎', name: 'red apple' },
      { emoji: '🍏', name: 'green apple' },
      { emoji: '🍐', name: 'pear' },
      { emoji: '🍑', name: 'peach' },
      { emoji: '🍒', name: 'cherries' },
      { emoji: '🍓', name: 'strawberry' },
      { emoji: '🫐', name: 'blueberries' },
      { emoji: '🥝', name: 'kiwi fruit' },
      { emoji: '🍅', name: 'tomato' },
      { emoji: '🫒', name: 'olive' },
      { emoji: '🥥', name: 'coconut' },
      { emoji: '🥑', name: 'avocado' },
      { emoji: '🍆', name: 'eggplant' },
      { emoji: '🥔', name: 'potato' },
      { emoji: '🥕', name: 'carrot' },
      { emoji: '🌽', name: 'ear of corn' },
      { emoji: '🌶', name: 'hot pepper' },
      { emoji: '🫑', name: 'bell pepper' },
      { emoji: '🥒', name: 'cucumber' },
      { emoji: '🥬', name: 'leafy green' },
      { emoji: '🥦', name: 'broccoli' },
      { emoji: '🧄', name: 'garlic' },
      { emoji: '🧅', name: 'onion' },
      { emoji: '🍄', name: 'mushroom' },
      { emoji: '🥜', name: 'peanuts' },
      { emoji: '🌰', name: 'chestnut' },
      { emoji: '🍞', name: 'bread' },
      { emoji: '🥐', name: 'croissant' },
      { emoji: '🥖', name: 'baguette bread' },
      { emoji: '🫓', name: 'flatbread' },
      { emoji: '🥨', name: 'pretzel' },
      { emoji: '🥯', name: 'bagel' },
      { emoji: '🥞', name: 'pancakes' },
      { emoji: '🧇', name: 'waffle' },
      { emoji: '🧀', name: 'cheese wedge' },
      { emoji: '🍖', name: 'meat on bone' },
      { emoji: '🍗', name: 'poultry leg' },
      { emoji: '🥩', name: 'cut of meat' },
      { emoji: '🥓', name: 'bacon' },
      { emoji: '🍔', name: 'hamburger' },
      { emoji: '🍟', name: 'french fries' },
      { emoji: '🍕', name: 'pizza' },
      { emoji: '🌭', name: 'hot dog' },
      { emoji: '🥪', name: 'sandwich' },
      { emoji: '🌮', name: 'taco' },
      { emoji: '🌯', name: 'burrito' },
      { emoji: '🫔', name: 'tamale' },
      { emoji: '🥙', name: 'stuffed flatbread' },
      { emoji: '🧆', name: 'falafel' },
      { emoji: '🥚', name: 'egg' },
      { emoji: '🍳', name: 'cooking' },
      { emoji: '🥘', name: 'shallow pan of food' },
      { emoji: '🍲', name: 'pot of food' },
      { emoji: '🫕', name: 'fondue' },
      { emoji: '🥣', name: 'bowl with spoon' },
      { emoji: '🥗', name: 'green salad' },
      { emoji: '🍿', name: 'popcorn' },
      { emoji: '🧈', name: 'butter' },
      { emoji: '🧂', name: 'salt' },
      { emoji: '🥫', name: 'canned food' },
      { emoji: '🍱', name: 'bento box' },
      { emoji: '🍘', name: 'rice cracker' },
      { emoji: '🍙', name: 'rice ball' },
      { emoji: '🍚', name: 'cooked rice' },
      { emoji: '🍛', name: 'curry rice' },
      { emoji: '🍜', name: 'steaming bowl' },
      { emoji: '🍝', name: 'spaghetti' },
      { emoji: '🍠', name: 'roasted sweet potato' },
      { emoji: '🍢', name: 'oden' },
      { emoji: '🍣', name: 'sushi' },
      { emoji: '🍤', name: 'fried shrimp' },
      { emoji: '🍥', name: 'fish cake with swirl' },
      { emoji: '🥮', name: 'moon cake' },
      { emoji: '🍡', name: 'dango' },
      { emoji: '🥟', name: 'dumpling' },
      { emoji: '🥠', name: 'fortune cookie' },
      { emoji: '🥡', name: 'takeout box' },
      { emoji: '🦀', name: 'crab' },
      { emoji: '🦞', name: 'lobster' },
      { emoji: '🦐', name: 'shrimp' },
      { emoji: '🦑', name: 'squid' },
      { emoji: '🦪', name: 'oyster' },
      { emoji: '🍦', name: 'soft ice cream' },
      { emoji: '🍧', name: 'shaved ice' },
      { emoji: '🍨', name: 'ice cream' },
      { emoji: '🍩', name: 'doughnut' },
      { emoji: '🍪', name: 'cookie' },
      { emoji: '🎂', name: 'birthday cake' },
      { emoji: '🍰', name: 'shortcake' },
      { emoji: '🧁', name: 'cupcake' },
      { emoji: '🥧', name: 'pie' },
      { emoji: '🍫', name: 'chocolate bar' },
      { emoji: '🍬', name: 'candy' },
      { emoji: '🍭', name: 'lollipop' },
      { emoji: '🍮', name: 'custard' },
      { emoji: '🍯', name: 'honey pot' },
      { emoji: '🍼', name: 'baby bottle' },
      { emoji: '🥛', name: 'glass of milk' },
      { emoji: '☕️', name: 'hot beverage' },
      { emoji: '🫖', name: 'teapot' },
      { emoji: '🍵', name: 'teacup without handle' },
      { emoji: '🍶', name: 'sake' },
      { emoji: '🍾', name: 'bottle with popping cork' },
      { emoji: '🍷', name: 'wine glass' },
      { emoji: '🍸', name: 'cocktail glass' },
      { emoji: '🍹', name: 'tropical drink' },
      { emoji: '🍺', name: 'beer mug' },
      { emoji: '🍻', name: 'clinking beer mugs' },
      { emoji: '🥂', name: 'clinking glasses' },
      { emoji: '🥃', name: 'tumbler glass' },
      { emoji: '🥤', name: 'cup with straw' },
      { emoji: '🧋', name: 'bubble tea' },
      { emoji: '🧃', name: 'beverage box' },
      { emoji: '🧉', name: 'mate' },
      { emoji: '🧊', name: 'ice' },
      { emoji: '🥢', name: 'chopsticks' },
      { emoji: '🍽', name: 'fork and knife with plate' },
      { emoji: '🍴', name: 'fork and knife' },
      { emoji: '🥄', name: 'spoon' },
    ],
  },
  {
    name: 'Symbols',
    emojis: [
      { emoji: '❤️', name: 'red heart' },
      { emoji: '🧡', name: 'orange heart' },
      { emoji: '💛', name: 'yellow heart' },
      { emoji: '💚', name: 'green heart' },
      { emoji: '💙', name: 'blue heart' },
      { emoji: '💜', name: 'purple heart' },
      { emoji: '🖤', name: 'black heart' },
      { emoji: '🤍', name: 'white heart' },
      { emoji: '🤎', name: 'brown heart' },
      { emoji: '💔', name: 'broken heart' },
      { emoji: '❣️', name: 'heart exclamation' },
      { emoji: '💕', name: 'two hearts' },
      { emoji: '💞', name: 'revolving hearts' },
      { emoji: '💓', name: 'beating heart' },
      { emoji: '💗', name: 'growing heart' },
      { emoji: '💖', name: 'sparkling heart' },
      { emoji: '💘', name: 'heart with arrow' },
      { emoji: '💝', name: 'heart with ribbon' },
      { emoji: '💟', name: 'heart decoration' },
      { emoji: '☮️', name: 'peace symbol' },
      { emoji: '✝️', name: 'latin cross' },
      { emoji: '☪️', name: 'star and crescent' },
      { emoji: '🕉', name: 'om' },
      { emoji: '☸️', name: 'wheel of dharma' },
      { emoji: '✡️', name: 'star of david' },
      { emoji: '🔯', name: 'dotted six-pointed star' },
      { emoji: '🕎', name: 'menorah' },
      { emoji: '☯️', name: 'yin yang' },
      { emoji: '☦️', name: 'orthodox cross' },
      { emoji: '🛐', name: 'place of worship' },
      { emoji: '⛎', name: 'ophiuchus' },
      { emoji: '♈️', name: 'aries' },
      { emoji: '♉️', name: 'taurus' },
      { emoji: '♊️', name: 'gemini' },
      { emoji: '♋️', name: 'cancer' },
      { emoji: '♌️', name: 'leo' },
      { emoji: '♍️', name: 'virgo' },
      { emoji: '♎️', name: 'libra' },
      { emoji: '♏️', name: 'scorpio' },
      { emoji: '♐️', name: 'sagittarius' },
      { emoji: '♑️', name: 'capricorn' },
      { emoji: '♒️', name: 'aquarius' },
      { emoji: '♓️', name: 'pisces' },
      { emoji: '🆔', name: 'id button' },
      { emoji: '⚛️', name: 'atom symbol' },
      { emoji: '🉑', name: 'japanese acceptable button' },
      { emoji: '☢️', name: 'radioactive' },
      { emoji: '☣️', name: 'biohazard' },
      { emoji: '📴', name: 'mobile phone off' },
      { emoji: '📳', name: 'vibration mode' },
      { emoji: '🈶', name: 'japanese not free of charge button' },
      { emoji: '🈚️', name: 'japanese free of charge button' },
      { emoji: '🈸', name: 'japanese application button' },
      { emoji: '🈺', name: 'japanese open for business button' },
      { emoji: '🈷️', name: 'japanese monthly amount button' },
      { emoji: '✴️', name: 'eight-pointed star' },
      { emoji: '🆚', name: 'vs button' },
      { emoji: '💮', name: 'white flower' },
      { emoji: '🉐', name: 'japanese bargain button' },
      { emoji: '㊙️', name: 'japanese secret button' },
      { emoji: '㊗️', name: 'japanese congratulation button' },
      { emoji: '🈴', name: 'japanese passing grade button' },
      { emoji: '🈵', name: 'japanese no vacancy button' },
      { emoji: '🈹', name: 'japanese discount button' },
      { emoji: '🈲', name: 'japanese prohibited button' },
      { emoji: '🅰️', name: 'a button' },
      { emoji: '🅱️', name: 'b button' },
      { emoji: '🆎', name: 'ab button' },
      { emoji: '🆑', name: 'cl button' },
      { emoji: '🅾️', name: 'o button' },
      { emoji: '🆘', name: 'sos button' },
      { emoji: '❌', name: 'cross mark' },
      { emoji: '⭕️', name: 'hollow red circle' },
      { emoji: '🛑', name: 'stop sign' },
      { emoji: '⛔️', name: 'no entry' },
      { emoji: '📛', name: 'name badge' },
      { emoji: '🚫', name: 'prohibited' },
      { emoji: '💯', name: 'hundred points' },
      { emoji: '💢', name: 'anger symbol' },
      { emoji: '♨️', name: 'hot springs' },
      { emoji: '🚷', name: 'no pedestrians' },
      { emoji: '🚯', name: 'no littering' },
      { emoji: '🚳', name: 'no bicycles' },
      { emoji: '🚱', name: 'non-potable water' },
      { emoji: '🔞', name: 'no one under eighteen' },
      { emoji: '📵', name: 'no mobile phones' },
      { emoji: '🚭', name: 'no smoking' },
      { emoji: '❗️', name: 'red exclamation mark' },
      { emoji: '❕', name: 'white exclamation mark' },
      { emoji: '❓', name: 'red question mark' },
      { emoji: '❔', name: 'white question mark' },
      { emoji: '‼️', name: 'double exclamation mark' },
      { emoji: '⁉️', name: 'exclamation question mark' },
      { emoji: '🔅', name: 'dim button' },
      { emoji: '🔆', name: 'bright button' },
      { emoji: '〽️', name: 'part alternation mark' },
      { emoji: '⚠️', name: 'warning' },
      { emoji: '🚸', name: 'children crossing' },
      { emoji: '🔱', name: 'trident emblem' },
      { emoji: '⚜️', name: 'fleur-de-lis' },
      { emoji: '🔰', name: 'japanese symbol for beginner' },
      { emoji: '♻️', name: 'recycling symbol' },
      { emoji: '✅', name: 'check mark button' },
      { emoji: '🈯️', name: 'japanese reserved button' },
      { emoji: '💹', name: 'chart increasing with yen' },
      { emoji: '❇️', name: 'sparkle' },
      { emoji: '✳️', name: 'eight-spoked asterisk' },
      { emoji: '❎', name: 'cross mark button' },
      { emoji: '🌐', name: 'globe with meridians' },
      { emoji: '💠', name: 'diamond with a dot' },
      { emoji: 'Ⓜ️', name: 'circled m' },
      { emoji: '🌀', name: 'cyclone' },
      { emoji: '💤', name: 'zzz' },
      { emoji: '🏧', name: 'atm sign' },
      { emoji: '🚾', name: 'water closet' },
      { emoji: '♿️', name: 'wheelchair symbol' },
      { emoji: '🅿️', name: 'p button' },
      { emoji: '🈳', name: 'japanese vacancy button' },
      { emoji: '🈂️', name: 'japanese service charge button' },
      { emoji: '🛂', name: 'passport control' },
      { emoji: '🛃', name: 'customs' },
      { emoji: '🛄', name: 'baggage claim' },
      { emoji: '🛅', name: 'left luggage' },
      { emoji: '🚹', name: 'men’s room' },
      { emoji: '🚺', name: 'women’s room' },
      { emoji: '🚼', name: 'baby symbol' },
      { emoji: '🚻', name: 'restroom' },
      { emoji: '🚮', name: 'litter in bin sign' },
      { emoji: '🎦', name: 'cinema' },
      { emoji: '📶', name: 'antenna bars' },
      { emoji: '🈁', name: 'japanese here button' },
      { emoji: '🔣', name: 'input symbols' },
      { emoji: '🔤', name: 'input latin letters' },
      { emoji: '🔡', name: 'input latin lowercase' },
      { emoji: '🔠', name: 'input latin uppercase' },
      { emoji: '🆖', name: 'ng button' },
      { emoji: '🆗', name: 'ok button' },
      { emoji: '🆙', name: 'up! button' },
      { emoji: '🆒', name: 'cool button' },
      { emoji: '🆕', name: 'new button' },
      { emoji: '🆓', name: 'free button' },
      { emoji: '0️⃣', name: 'keycap: 0' },
      { emoji: '1️⃣', name: 'keycap: 1' },
      { emoji: '2️⃣', name: 'keycap: 2' },
      { emoji: '3️⃣', name: 'keycap: 3' },
      { emoji: '4️⃣', name: 'keycap: 4' },
      { emoji: '5️⃣', name: 'keycap: 5' },
      { emoji: '6️⃣', name: 'keycap: 6' },
      { emoji: '7️⃣', name: 'keycap: 7' },
      { emoji: '8️⃣', name: 'keycap: 8' },
      { emoji: '9️⃣', name: 'keycap: 9' },
      { emoji: '🔟', name: 'keycap: 10' },
      { emoji: '🔢', name: 'input numbers' },
      { emoji: '#️⃣', name: 'keycap: #' },
      { emoji: '*️⃣', name: 'keycap: *' },
      { emoji: '▶️', name: 'play button' },
      { emoji: '⏸', name: 'pause button' },
      { emoji: '⏯', name: 'play or pause button' },
      { emoji: '⏹', name: 'stop button' },
      { emoji: '⏺', name: 'record button' },
      { emoji: '⏭', name: 'next track button' },
      { emoji: '⏮', name: 'last track button' },
      { emoji: '⏩', name: 'fast-forward button' },
      { emoji: '⏪', name: 'fast reverse button' },
      { emoji: '⏫', name: 'fast up button' },
      { emoji: '⏬', name: 'fast down button' },
      { emoji: '◀️', name: 'reverse button' },
      { emoji: '🔼', name: 'upwards button' },
      { emoji: '🔽', name: 'downwards button' },
      { emoji: '➡️', name: 'right arrow' },
      { emoji: '⬅️', name: 'left arrow' },
      { emoji: '⬆️', name: 'up arrow' },
      { emoji: '⬇️', name: 'down arrow' },
      { emoji: '↗️', name: 'up-right arrow' },
      { emoji: '↘️', name: 'down-right arrow' },
      { emoji: '↙️', name: 'down-left arrow' },
      { emoji: '↖️', name: 'up-left arrow' },
      { emoji: '↕️', name: 'up-down arrow' },
      { emoji: '↔️', name: 'left-right arrow' },
      { emoji: '↪️', name: 'right arrow curving left' },
      { emoji: '↩️', name: 'left arrow curving right' },
      { emoji: '⤴️', name: 'right arrow curving up' },
      { emoji: '⤵️', name: 'right arrow curving down' },
      { emoji: '🔀', name: 'shuffle tracks button' },
      { emoji: '🔁', name: 'repeat button' },
      { emoji: '🔂', name: 'repeat single button' },
      { emoji: '🔄', name: 'counterclockwise arrows button' },
      { emoji: '🔃', name: 'clockwise vertical arrows' },
      { emoji: '🎵', name: 'musical note' },
      { emoji: '🎶', name: 'musical notes' },
      { emoji: '➕', name: 'plus' },
      { emoji: '➖', name: 'minus' },
      { emoji: '➗', name: 'divide' },
      { emoji: '✖️', name: 'multiply' },
      { emoji: '♾', name: 'infinity' },
      { emoji: '💲', name: 'heavy dollar sign' },
      // FIX: Removed stray hyphen causing a type error.
      { emoji: '💱', name: 'currency exchange' },
      { emoji: '™️', name: 'trade mark' },
      { emoji: '©️', name: 'copyright' },
      { emoji: '®️', name: 'registered' },
      { emoji: '〰️', name: 'wavy dash' },
      { emoji: '➰', name: 'curly loop' },
      { emoji: '➿', name: 'double curly loop' },
      { emoji: '🔚', name: 'end arrow' },
      { emoji: '🔙', name: 'back arrow' },
      { emoji: '🔛', name: 'on! arrow' },
      { emoji: '🔝', name: 'top arrow' },
      { emoji: '🔜', name: 'soon arrow' },
      { emoji: '✔️', name: 'check mark' },
      { emoji: '☑️', name: 'check box with check' },
      { emoji: '🔘', name: 'radio button' },
      { emoji: '🔴', name: 'red circle' },
      { emoji: '🟠', name: 'orange circle' },
      { emoji: '🟡', name: 'yellow circle' },
      { emoji: '🟢', name: 'green circle' },
      { emoji: '🔵', name: 'blue circle' },
      { emoji: '🟣', name: 'purple circle' },
      { emoji: '⚫️', name: 'black circle' },
      { emoji: '⚪️', name: 'white circle' },
      { emoji: '🟤', name: 'brown circle' },
      { emoji: '🔺', name: 'red triangle pointed up' },
      { emoji: '🔻', name: 'red triangle pointed down' },
      { emoji: '🔳', name: 'white square button' },
      { emoji: '🔲', name: 'black square button' },
      { emoji: '▪️', name: 'black small square' },
      { emoji: '▫️', name: 'white small square' },
      { emoji: '◾️', name: 'black medium-small square' },
      { emoji: '◽️', name: 'white medium-small square' },
      { emoji: '◼️', name: 'black medium square' },
      { emoji: '◻️', name: 'white medium square' },
      { emoji: '🟥', name: 'red square' },
      { emoji: '🟧', name: 'orange square' },
      { emoji: '🟨', name: 'yellow square' },
      { emoji: '🟩', name: 'green square' },
      { emoji: '🟦', name: 'blue square' },
      { emoji: '🟪', name: 'purple square' },
      { emoji: '⬛️', name: 'black large square' },
      { emoji: '⬜️', name: 'white large square' },
      { emoji: '🟫', name: 'brown square' },
      { emoji: '🔶', name: 'large orange diamond' },
      { emoji: '🔷', name: 'large blue diamond' },
      { emoji: '🔸', name: 'small orange diamond' },
      { emoji: '🔹', name: 'small blue diamond' },
      { emoji: '💬', name: 'speech balloon' },
      { emoji: '💭', name: 'thought balloon' },
      { emoji: '🃏', name: 'joker' },
      { emoji: '🎴', name: 'flower playing cards' },
      { emoji: '🀄️', name: 'mahjong red dragon' },
    ],
  },
];