import type { KaomojiTopCategory } from '../types';

export const kaomojiData: KaomojiTopCategory[] = [
  {
    category: 'Positive Emotions',
    subCategories: [
      {
        subCategory: 'Joy',
        description: 'Express pure happiness and delight with our collection of Joy kaomojis. These expressive faces are perfect for celebrating good news, sharing excitement with friends, or simply spreading positivity. Featuring upturned eyes, cheerful smiles, and often accompanied by triumphant gestures, these kaomojis radiate infectious enthusiasm. Use them to brighten someone\'s day, react to a wonderful surprise, or convey a sense of lighthearted fun in your conversations. From simple smiles to ecstatic celebrations, this category has the perfect joyful expression for any happy occasion.',
        kaomojis: [
          { name: "Delighted", value: "(* ^ ω ^)" },
          { name: "Warm Smile", value: "(´ ∀ ` *)" },
          { name: "Playful Joy", value: "٩(◕‿◕｡)۶" },
          { name: "Excited Sparkles", value: "☆*:.｡.o(≧▽≦)o.｡.:*☆" },
          { name: "Cheerful Wink", value: "(o^▽^o)" },
          { name: "Radiant Laugh", value: "(⌒▽⌒)☆" },
          { name: "Pleased", value: "<(￣︶￣)>" },
          { name: "Shy Happiness", value: "。.:☆*:･'(*⌒―⌒*)))" },
          { name: "Cheerful Wave", value: "ヽ(・∀・)ﾉ" },
          { name: "Gentle Smile", value: "(´｡• ω •｡`)" },
          { name: "Calm Mood", value: "(￣ω￣)" },
          { name: "Embarrassed Laugh", value: "｀;:゛;｀;･(°ε° )" },
          { name: "Curious Look", value: "(o･ω･o)" },
          { name: "Happy Face", value: "(＠＾◡＾)" },
          { name: "Energetic Jump", value: "ヽ(*・ω・)ﾉ" },
          { name: "Laughing Hard", value: "(o_ _)ﾉ彡☆" },
          { name: "Grateful", value: "(^人^)" },
          { name: "Joyful Expression", value: "(o´▽`o)" },
          { name: "Smiling Sweetly", value: "(*´▽`*)" },
          { name: "Laughing Tears", value: "｡ﾟ( ﾟ^∀^ﾟ)ﾟ｡" },
          { name: "Soft Smile", value: "( ´ ω ` )" },
          { name: "Excited Cheer", value: "(((o(*°▽°*)o)))" },
          { name: "Bright Smile", value: "(≧◡≦)" },
          { name: "Friendly Grin", value: "(o´∀`o)" },
          { name: "Cute Mood", value: "(´• ω •`)" },
          { name: "Happy Laugh", value: "(＾▽＾)" },
          { name: "Gentle Happiness", value: "(⌒ω⌒)" },
          { name: "Approval Sign", value: "∑d(°∀°d)" },
          { name: "Playful Pose", value: "╰(▔∀▔)╯" },
          { name: "Content Smile", value: "(─‿‿─)" },
          { name: "Happy Glow", value: "(*^‿^*)" },
          { name: "Cheerful Spirit", value: "ヽ(o^ ^o)ﾉ" },
          { name: "Starry Eyes", value: "(✯◡✯)" },
          { name: "Charming Smile", value: "(◕‿◕)" },
          { name: "Overjoyed", value: "(*≧ω≦*)" },
          { name: "Sparkling Joy", value: "(☆▽☆)" },
          { name: "Beaming", value: "(⌒‿⌒)" },
          { name: "Ecstatic Cheer", value: "＼(≧▽≦)／" },
          { name: "Lively Dance", value: "ヽ(o＾▽＾o)ノ" },
          { name: "Friendly Greeting", value: "☆ ～('▽^人)" },
          { name: "Playful Beam", value: "(*°▽°*)" },
          { name: "Energetic Jump 2", value: "٩(｡•́‿•̀｡)۶" },
          { name: "Sparkle Eyes", value: "(✧ω✧)" },
          { name: "Joyful Jump", value: "ヽ(*⌒▽⌒*)ﾉ" },
          { name: "Blushing Smile", value: "(´｡• ᵕ •｡`)" },
          { name: "Happy Calm", value: "( ´ ▽ ` )" },
          { name: "Relaxed", value: "(￣▽￣)" },
          { name: "Heartfelt Smile", value: "╰(*´︶`*)╯" },
          { name: "Excited Burst", value: "ヽ(>∀<☆)ノ" },
          { name: "Ecstatic", value: "o(≧▽≦)o" },
          { name: "Starry Wonder", value: "(☆ω☆)" },
          { name: "Peaceful Rest", value: "(っ˘ω˘ς )" },
          { name: "Triumphant Cheer", value: "＼(￣▽￣)／" },
          { name: "Satisfied", value: "(*¯︶¯*)" },
          { name: "Victory Pose", value: "＼(＾▽＾)／" },
          { name: "Joyful Energy", value: "٩(◕‿◕)۶" },
          { name: "Serene Mood", value: "(o˘◡˘o)" },
          { name: "Star Power", value: "\\(★ω★)/" },
          { name: "Happy Shout", value: "\\(^ヮ^)/" },
          { name: "Cheerful Blush", value: "(〃＾▽＾〃)" },
          { name: "Excited Cast", value: "(╯✧▽✧)╯" },
          { name: "Energetic Burst", value: "o(>ω<)o" },
          { name: "Proud Smile", value: "o( ❛ᴗ❛ )o" },
          { name: "Crying Joy", value: "｡ﾟ(TヮT)ﾟ｡" },
          { name: "Confident Smile", value: "( ‾́ ◡ ‾́ )" },
          { name: "Playful Wave", value: "(ﾉ´ヮ`)ﾉ*: ･ﾟ" },
          { name: "Thumbs Up", value: "(b ᵔ▽ᵔ)b" },
          { name: "Victory Fist", value: "(๑˃ᴗ˂)ﻭ" },
          { name: "Peaceful Smile", value: "(๑˘︶˘๑)" },
          { name: "Curious Face", value: "( ˙꒳​˙ )" },
          { name: "Crying Cutely", value: "(*꒦ິ꒳꒦ີ)" },
          { name: "Sparkling Excitement", value: "°˖✧◝(⁰▿⁰)◜✧˖°" },
          { name: "Soft Emotion", value: "(´･ᴗ･ ` )" },
          { name: "Excited Dance", value: "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧" },
          { name: "Gentle Contentment", value: "(„• ֊ •„)" },
          { name: "Sweet Look", value: "(.❛ ᴗ ❛.)" },
          { name: "Relaxed Cheer", value: "(⁀ᗢ⁀)" },
          { name: "Smug Smile", value: "(￢‿￢ )" },
          { name: "Playful Smirk", value: "(¬‿¬ )" },
          { name: "Cool Approval", value: "(*￣▽￣)b" },
          { name: "Optimistic", value: "( ˙▿˙ )" },
          { name: "Chill Mood", value: "(¯▿¯)" },
          { name: "Cheery Look", value: "( ◕▿◕ )" },
          { name: "Joyful Yell", value: "＼(٥⁀▽⁀ )／" },
          { name: "Soft Smile 2", value: "(„• ᴗ •„)" },
          { name: "Kind Smile", value: "(ᵔ◡ᵔ)" },
          { name: "Relaxed Cheer 2", value: "( ´ ▿ ` )" },
          { name: "Delightful", value: "(๑>◡<๑)" },
          { name: "Cute Expression", value: "( = ⩊ = )" },
          { name: "Shy Grin", value: "( ´ ꒳ ` )" },
          { name: "Happy Wave", value: "⸜( ´ ꒳ ` )⸝" },
          { name: "Hugging Cheer", value: "⸜(⸝⸝⸝´꒳`⸝⸝⸝)⸝" },
          { name: "Jumping Joy", value: "⸜(*ˊᗜˋ*)⸝" },
          { name: "Cute Wave", value: "⸜( *ˊᵕˋ* )⸝" },
          { name: "Playful Face", value: "(>⩊<)" },
          { name: "Super Happy", value: "(ᗒ⩊ᗕ)" },
          { name: "Smiling Eyes", value: "(ᵔ⩊ᵔ)" },
          { name: "Gentle Joy", value: "( ᵔ ⩊ ᵔ )" },
          { name: "Soft Content", value: "(•⩊•)" },
          { name: "Calm Delight", value: "( • ⩊ • )" }
        ],
      },
      {
        subCategory: 'Love',
        description: 'Dive into the world of affection and romance with our Love kaomojis. This category is filled with characters perfect for expressing heartfelt emotions, from a budding crush to deep, unwavering love. You\'ll find kaomojis blushing shyly, sending kisses, offering hearts, and locked in warm embraces. They are ideal for sweet messages to your significant other, showing appreciation for a dear friend, or reacting to something incredibly adorable. Let these charming text faces convey the warmth and tenderness that words alone sometimes cannot capture.',
        kaomojis:[
          { name: "Sending Love", value: "(ﾉ´ з `)ノ" },
          { name: "Shy Heart", value: "(♡μ_μ)" },
          { name: "Sweet Smile", value: "(*^^*)♡" },
          { name: "Blowing Kiss", value: "☆⌒ヽ(*'､^*)chu" },
          { name: "Dreamy Love", value: "(♡-_-♡)" },
          { name: "Kiss Gesture", value: "(￣ε￣＠)" },
          { name: "Love Hug", value: "ヽ(♡‿♡)ノ" },
          { name: "Waving Heart", value: "( ´ ∀ `)ノ～ ♡" },
          { name: "Gentle Love", value: "(─‿‿─)♡" },
          { name: "Blushing Heart", value: "(´｡• ᵕ •｡`) ♡" },
          { name: "In Love", value: "(*♡∀♡)" },
          { name: "Shy Kiss", value: "(｡・//ε//・｡)" },
          { name: "Warm Heart", value: "(´ ω `♡)" },
          { name: "Caring Heart", value: "♡( ◡‿◡ )" },
          { name: "Lovely Smile", value: "(◕‿◕)♡" },
          { name: "Dreamy Heart", value: "(/▽＼*)｡o○♡" },
          { name: "Peaceful Love", value: "(ღ˘⌣˘ღ)" },
          { name: "Excited Heart", value: "(♡°▽°♡)" },
          { name: "Tender Heart", value: "♡(｡- ω -)" },
          { name: "Heartfelt Greeting", value: "♡ ～('▽^人)" },
          { name: "Affectionate Look", value: "(´• ω •`) ♡" },
          { name: "Soft Kiss", value: "(´ ε ` )♡" },
          { name: "Cute Blush", value: "(´｡• ω •｡`) ♡" },
          { name: "Daydreaming Love", value: "( ´ ▽ ` ).｡ｏ♡" },
          { name: "Loving Embrace", value: "╰(*´︶`*)╯♡" },
          { name: "Serene Heart", value: "(*˘︶˘*).｡.:*♡" },
          { name: "Pure Love", value: "(♡˙︶˙♡)" },
          { name: "Joyful Heart", value: "♡＼(￣▽￣)／♡" },
          { name: "Overjoyed Love", value: "(≧◡≦) ♡" },
          { name: "Happy Heart", value: "(⌒▽⌒)♡" },
          { name: "Kiss Face", value: "(*¯ ³¯*)♡" },
          { name: "Loving Kiss", value: "(っ˘з(˘⌣˘ ) ♡" },
          { name: "Cute Couple", value: "♡ (˘▽˘>ԅ( ˘⌣˘)" },
          { name: "Mutual Love", value: "( ˘⌣˘)♡(˘⌣˘ )" },
          { name: "Couple Hug", value: "(/^-^(^ ^*)/ ♡" },
          { name: "Playful Kiss", value: "٩(♡ε♡)۶" },
          { name: "Pouting Love", value: "σ(≧ε≦σ) ♡" },
          { name: "Flirty Wink", value: "♡ (⇀ 3 ↼)" },
          { name: "Sassy Kiss", value: "♡ (￣З￣)" },
          { name: "Heart Eyes", value: "(❤ω❤)" },
          { name: "Love Greeting", value: "(˘∀˘)/(μ‿μ) ❤" },
          { name: "Sweet Hug", value: "❤ (ɔˆз(ˆ⌣ˆc)" },
          { name: "Loving Gaze", value: "(´♡‿♡`)" },
          { name: "Cute Love", value: "(°◡°♡)" },
          { name: "Arrow of Love", value: "Σ>―(〃°ω°〃)♡→" },
          { name: "Soft Smile Love", value: "(´,,•ω•,,)♡" },
          { name: "Calm Heart", value: "(´꒳`)♡" },
          { name: "Flirty Look", value: "♡(>ᴗ•)" },
          { name: "Love Overload", value: "(❤⩊❤)[=_=](☆ε☆)" },
          { name: "Gentle Love 2", value: "( ´ ꒳ ` ) ♡" },
          { name: "Sleepy Heart", value: "(˘˘ ♡)" },
          { name: "Dreamy Thought", value: "(´ ˘ `).｡oO (♡)" }
        ],
      },
      {
        subCategory: 'Embarrassment',
        description: 'Navigate those awkward and shy moments with our collection of Embarrassment kaomojis. These text faces perfectly capture the feeling of being flustered, bashful, or shy. Featuring blushing cheeks, averted eyes, and sometimes frantic, fidgeting hands, they are great for reacting to a compliment, admitting a silly mistake, or when you just don\'t know what to say. Whether you\'re feeling a little self-conscious or completely mortified, these kaomojis add a relatable and human touch to your digital interactions, showing vulnerability in a cute and endearing way.',
        kaomojis: [
          { name: "Awkward Smile", value: "(⌒_⌒;)" },
          { name: "Gentle Smile", value: "(o^ ^o)" },
          { name: "Shy Cover", value: "(*/ω＼)" },
          { name: "Embarrassed Blush", value: "(*/。＼)" },
          { name: "Hiding Face", value: "(*/_＼)" },
          { name: "Blushing Bashful", value: "(*ﾉωﾉ)" },
          { name: "Shy Downcast", value: "(o-_-o)" },
          { name: "Timid Smile", value: "(*μ_μ)" },
          { name: "Sweet Smile", value: "( ◡‿◡ *)" },
          { name: "Soft Grin", value: "(ᵔ.ᵔ)" },
          { name: "Laughing Bashfully", value: "(*ﾉ∀`*)" },
          { name: "Blushing Smile", value: "(//▽//)" },
          { name: "Flushed Face", value: "(//ω//)" },
          { name: "Bashful Cheer", value: "(ノ*°▽°*)" },
          { name: "Cute Bashful", value: "(*^.^*)" },
          { name: "Hiding Smile", value: "(*ﾉ▽ﾉ)" },
          { name: "Nervous Laugh", value: "(￣▽￣*)ゞ" },
          { name: "Flustered Blush", value: "(⁄ ⁄•⁄ω⁄•⁄ ⁄)" },
          { name: "Embarrassed Laugh", value: "(*/▽＼*)" },
          { name: "Shy Hide", value: "(⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)" },
          { name: "Sly Blush", value: "(„ಡωಡ„)" },
          { name: "Awkward Handwave", value: "(ง ื▿ ื)ว" },
          { name: "Cute Blush", value: "( 〃▽〃)" },
          { name: "Peeking Shy", value: "(/▿＼ )" }
        ],
      },
      {
        subCategory: 'Sympathy',
        description: 'Show your support and compassion with our Sympathy kaomojis. This collection is designed to help you offer comfort and understanding to others during difficult times. These kaomojis often feature gentle, caring expressions, offering a comforting pat, a warm hug, or a shoulder to lean on. They are perfect for responding to sad news, encouraging a friend who is feeling down, or simply letting someone know you\'re there for them. In moments where words may fall short, a thoughtful kaomoji can be a powerful way to express empathy and connect on an emotional level.',
        kaomojis: [
          { name: "Comforting Cry", value: "(ノ_<。)ヾ(´ ▽ ` )" },
          { name: "Soothing Tears", value: "｡･ﾟ･(ﾉД`)ヽ(￣ω￣ )" },
          { name: "Gentle Consolation", value: "ρ(- ω -、)ヾ(￣ω￣; )" },
          { name: "Pat on Shoulder", value: "ヽ(￣ω￣(。。 )ゝ" },
          { name: "Hug of Comfort", value: "(*´ I `)ﾉﾟ(ﾉД｀ﾟ)ﾟ｡" },
          { name: "Reassuring Friend", value: "ヽ(~_~(・_・ )ゝ" },
          { name: "Sympathy Hug", value: "(ﾉ_；)ヾ(´ ∀ ` )" },
          { name: "Wiping Tears", value: "(; ω ; )ヾ(´∀`* )" },
          { name: "Soft Consolation", value: "(*´ー)ﾉ(ノд`)" },
          { name: "Supportive Hug", value: "(´-ω-`( _ _ )" },
          { name: "Tender Comfort", value: "(っ´ω`)ﾉ(╥ω╥)" },
          { name: "Cheering Up", value: "(ｏ・_・)ノ”(ノ_<、)" }
        ],
      },
    ],
  },
  {
    category: 'Negative Emotions',
    subCategories: [
      {
        subCategory: 'Dissatisfaction',
        description: 'Express feelings of annoyance, disapproval, and general discontent with our Dissatisfaction kaomojis. This category is perfect for when things aren\'t going your way or when you need to show you\'re unimpressed. Featuring disapproving glares, skeptical expressions, and frustrated sighs, these kaomojis capture that "I am not amused" feeling. Use them to react to a bad joke, complain about a frustrating situation, or show your skepticism. They add a touch of relatable grumpiness to your chats, letting you vent your minor frustrations in a humorous and expressive manner.',
        kaomojis: [
          { name: "Frustrated", value: "(＃＞＜)" },
          { name: "Disappointed", value: "(；⌣̀_⌣́)" },
          { name: "Upset", value: "☆ｏ(＞＜；)○" },
          { name: "Annoyed", value: "(￣ ￣|||)" },
          { name: "Shocked", value: "(；￣Д￣)" },
          { name: "Surprised", value: "(￣□￣」)" },
          { name: "Angry Shout", value: "(＃￣0￣)" },
          { name: "Irritated", value: "(＃￣ω￣)" },
          { name: "Skeptical", value: "(￢_￢;)" },
          { name: "Grimacing", value: "(＞ｍ＜)" },
          { name: "Yelling", value: "(」°ロ°)」" },
          { name: "Embarrassed Frustration", value: "(〃＞＿＜;〃)" },
          { name: "Annoyed Smile", value: "(＾＾＃)" },
          { name: "Sad", value: "(︶︹︺)" },
          { name: "Angry", value: "(￣ヘ￣)" },
          { name: "Displeased", value: "<(￣ ﹌ ￣)>" },
          { name: "Frowning", value: "(￣︿￣)" },
          { name: "Crying in Anger", value: "(＞﹏＜)" },
          { name: "Sullen", value: "(--_--)" },
          { name: "Raging", value: "凸(￣ヘ￣)" },
          { name: "Angry Yell", value: "ヾ( ￣O￣)ツ" },
          { name: "Annoyed Stare", value: "(⇀‸↼‶)" },
          { name: "In Pain", value: "o(>< )o" },
          { name: "Screaming", value: "(」＞＜)」" },
          { name: "Crying Rage", value: "(ᗒᗣᗕ)՞" },
          { name: "Unamused", value: "(눈_눈)" }
        ],
      },
      {
        subCategory: 'Anger',
        description: 'Unleash your frustration and fury with our collection of Anger kaomojis. When you\'re feeling mad, these are the text faces you need. This category is filled with intense expressions, from menacing glares and clenched teeth to full-blown table flips. They are perfect for showing you\'re seriously annoyed, raging at a game, or just having a bad day. These kaomojis pack a visual punch, effectively communicating high levels of irritation and anger. Whether you\'re mildly irritated or boiling with rage, you\'ll find the right expression here to let off some steam.',
        kaomojis: [
          { name: "Annoyed", value: "(＃`Д´)" },
          { name: "Irritated", value: "(`皿´＃)" },
          { name: "Pouting", value: "( ` ω ´ )" },
          { name: "Yelling", value: "ヽ( `д´*)ノ" },
          { name: "Determined Anger", value: "(・`ω´・)" },
          { name: "Grumpy", value: "(`ー´)" },
          { name: "Furious", value: "ヽ(`⌒´メ)ノ" },
          { name: "Middle Finger Rage", value: "凸(`△´＃)" },
          { name: "Displeased", value: "( `ε´ )" },
          { name: "Evil Laugh", value: "ψ( ` ∇ ´ )ψ" },
          { name: "Throwing Tantrum", value: "ヾ(`ヘ´)ﾉﾞ" },
          { name: "Frustrated", value: "ヽ(‵﹏´)ノ" },
          { name: "Mad Look", value: "(ﾒ` ﾛ ´)" },
          { name: "Raging", value: "(╬`益´)" },
          { name: "Double Middle Finger", value: "┌∩┐(◣_◢)┌∩┐" },
          { name: "Extreme Rage", value: "凸( ` ﾛ ´ )凸" },
          { name: "Shocked Fury", value: "Σ(▼□▼メ)" },
          { name: "Boiling Mad", value: "(°ㅂ°╬)" },
          { name: "Evil Scheme", value: "ψ(▼へ▼メ)～→" },
          { name: "Rampaging", value: "(ノ°益°)ノ" },
          { name: "Grinding Teeth", value: "(҂ `з´ )" },
          { name: "Demonic Rage", value: "(‡▼益▼)" },
          { name: "Enraged Gesture", value: "(҂` ﾛ ´)凸" },
          { name: "Fuming", value: "((╬◣﹏◢))" },
          { name: "Explosive Anger", value: "٩(╬ʘ益ʘ╬)۶" },
          { name: "Intense Rage", value: "(╬ Ò﹏Ó)" },
          { name: "Power Rage", value: "＼＼٩(๑`^´๑)۶／／" },
          { name: "Offended", value: "(凸ಠ益ಠ)凸" },
          { name: "Sinister Laugh", value: "↑_(ΦwΦ)Ψ" },
          { name: "Scheming Evil", value: "←~(Ψ▼ｰ▼)∈" },
          { name: "Furious Power", value: "୧((#Φ益Φ#))୨" },
          { name: "Ultimate Rage", value: "٩(ఠ益ఠ)۶" },
          { name: "Crying Anger", value: "(ﾉಥ益ಥ)ﾉ" },
          { name: "Silent Fury", value: "(≖､≖╬)" }
        ],
      },
      {
        subCategory: 'Sadness',
        description: 'Convey feelings of sorrow, grief, and disappointment with our Sadness kaomojis. This collection captures the many shades of being sad, from quiet melancholy to streams of tears. Featuring downturned mouths, teary eyes, and sorrowful expressions, these text faces are perfect for when you\'re feeling down, sharing bad news, or expressing sympathy. They provide a way to communicate your emotional state visually, allowing for a more heartfelt and genuine connection. Whether you\'re heartbroken or just feeling blue, these kaomojis can help you express what you\'re going through.',
        kaomojis: [
          { name: "Crying Softly", value: "(ノ_<。)" },
          { name: "Downcast", value: "(-_-)" },
          { name: "Sleepy Sadness", value: "(´-ω-`)" },
          { name: "Tearful Cover", value: ".･ﾟﾟ･(／ω＼)･ﾟﾟ･." },
          { name: "Quiet Sadness", value: "(μ_μ)" },
          { name: "Crying Loudly", value: "(ﾉД`)" },
          { name: "Sorrowful Tears", value: "(-ω-、)" },
          { name: "Weeping Heart", value: "。゜゜(´Ｏ`) ゜゜。" },
          { name: "Heartbroken", value: "o(TヘTo)" },
          { name: "Sad Tears", value: "( ; ω ; )" },
          { name: "Disappointed", value: "(｡╯︵╰｡)" },
          { name: "Desperate Cry", value: "｡･ﾟﾟ*(>д<)*ﾟﾟ･｡" },
          { name: "Melancholy", value: "( ﾟ，_ゝ｀)" },
          { name: "Weary", value: "(个_个)" },
          { name: "Sobbing Face", value: "(╯︵╰,)" },
          { name: "Emotional Breakdown", value: "｡･ﾟ(ﾟ><ﾟ)ﾟ･｡" },
          { name: "Tearful", value: "( ╥ω╥ )" },
          { name: "Depressed", value: "(╯_╰)" },
          { name: "Deep Sadness", value: "(╥_╥)" },
          { name: "Painful Cry", value: ".｡･ﾟﾟ･(＞_＜)･ﾟﾟ･｡." },
          { name: "Hiding Tears", value: "(／ˍ・、)" },
          { name: "Crying Face", value: "(ノ_<、)" },
          { name: "Heart in Pain", value: "(╥﹏╥)" },
          { name: "Tearfall", value: "｡ﾟ(｡ﾉωヽ｡)ﾟ｡" },
          { name: "Soft Cry", value: "(つω`｡)" },
          { name: "Heavy Tears", value: "(｡T ω T｡)" },
          { name: "Quiet Weep", value: "(ﾉω･､)" },
          { name: "Emotional Hurt", value: "･ﾟ･(｡>ω<｡)･ﾟ･" },
          { name: "Crying Classic", value: "(T_T)" },
          { name: "Frustration", value: "(>_<)" },
          { name: "Comfort Hug", value: "(っ˘̩╭╮˘̩)っ" },
          { name: "Painful Tears", value: "｡ﾟ･ (>﹏<) ･ﾟ｡" },
          { name: "Hopeless Cry", value: "o(〒﹏〒)o" },
          { name: "Disheartened", value: "(｡•́︿•̀｡)" },
          { name: "Crying Hard", value: "(ಥ﹏ಥ)" },
          { name: "Despair", value: "(ಡ‸ಡ)" }
        ],
      },
      {
        subCategory: 'Pain',
        description: 'Express physical or emotional hurt with our Pain kaomojis. This selection is for those moments when you need to show you\'re suffering, whether it\'s from a headache, a heartbreak, or a clumsy accident. These kaomojis often feature clenched or squinting eyes, pained expressions, and sometimes even visual representations of injury like bandages. They are useful for telling someone you\'re not feeling well, reacting to a painful story, or just exclaiming "ouch!" in a digital conversation. They offer a clear and immediate way to communicate distress and suffering.',
        kaomojis: [
          { name: "Frustrated", value: "~(>_<~)" },
          { name: "Pained Sparkle", value: "☆⌒(> _ <)" },
          { name: "Crying Sparkle", value: "☆⌒(>。<)" },
          { name: "Shocked Eyes", value: "(☆_@)" },
          { name: "Dead Tired", value: "(×_×)" },
          { name: "Exhausted", value: "(x_x)" },
          { name: "Dead Tired Sparkle", value: "(×_×)⌒☆" },
          { name: "Exhausted Sparkle", value: "(x_x)⌒☆" },
          { name: "Crying Hard", value: "(×﹏×)" },
          { name: "Frustrated Star", value: "☆(＃××)" },
          { name: "Tired Face", value: "(＋_＋)" },
          { name: "Confused", value: "[ ± _ ± ]" },
          { name: "Overwhelmed", value: "٩(× ×)۶" },
          { name: "Desperate", value: "_:(´ཀ`」 ∠):_" },
          { name: "Annoyed", value: "(ﾒ﹏ﾒ)" }
        ],
      },
      {
        subCategory: 'Fear',
        description: 'Capture feelings of fear, shock, and anxiety with our collection of Fear kaomojis. These text faces are perfect for reacting to scary movies, surprising news, or any situation that makes you jump. Featuring wide eyes, open mouths, and sometimes trembling or sweating effects, these kaomojis effectively convey a sense of alarm and terror. Use them when you\'re startled, worried about something, or trying to describe a suspenseful moment. They add a dramatic flair to your messages, clearly communicating that you\'re spooked, nervous, or completely terrified.',
        kaomojis: [
          { name: "Shy Embarrassment", value: "(ノωヽ)" },
          { name: "Hiding Face", value: "(／。＼)" },
          { name: "Crying Slightly", value: "(ﾉ_ヽ)" },
          { name: "Frustrated Cry", value: "..・ヾ(。＞＜)シ" },
          { name: "Angry Shock", value: "(″ロ゛)" },
          { name: "Overwhelmed", value: "(;;;*_*)" },
          { name: "Praying Worried", value: "(・人・)" },
          { name: "Shocked", value: "＼(〇_ｏ)／" },
          { name: "Blushing Shy", value: "(/ω＼)" },
          { name: "Hiding Head", value: "(/_＼)" },
          { name: "Extreme Frustration", value: "〜(＞＜)〜" },
          { name: "Terrified", value: "Σ(°△°|||)︴" },
          { name: "Crying Intensely", value: "(((＞＜)))" },
          { name: "Exasperated", value: "{{ (>_<) }}" },
          { name: "Shocked Panic", value: "＼(º □ º l|l)/" },
          { name: "Extreme Panic", value: "〣( ºΔº )〣" },
          { name: "Confused Chaos", value: "▓▒░(°◡°)░▒▓" },
          { name: "Shocked Sweat", value: "(°□°;)" },
          { name: "Terrified Yell", value: "Σ(°ロ°)!!!" }
        ],
      },
    ],
  },
  {
    category: 'Neutral Emotions',
    subCategories: [
      {
        subCategory: 'Indifference',
        description: 'For moments when you\'re feeling neutral, unbothered, or simply don\'t have a strong opinion, our Indifference kaomojis are the perfect choice. This collection includes the classic shrug, blank stares, and other noncommittal expressions. They are incredibly versatile for situations where you want to convey apathy, uncertainty, or a simple "I don\'t know." Use them to respond to a question you can\'t answer, to show you\'re impartial in a discussion, or to react with a calm, unimpressed demeanor. These kaomojis are the epitome of digital nonchalance.',
        kaomojis: [
          { name: "Annoyed Shrug", value: "ヽ(ー_ー )ノ" },
          { name: "Casual Shrug", value: "ヽ(´ー` )┌" },
          { name: "Meh Shrug", value: "┐(‘～` )┌" },
          { name: "Exasperated Shrug", value: "ヽ(　￣д￣)ノ" },
          { name: "Frustrated Shrug", value: "┐(￣ヘ￣)┌" },
          { name: "Indifferent Shrug", value: "ヽ(￣～￣　)ノ" },
          { name: "Confused Shrug", value: "╮(￣_￣)╭" },
          { name: "Skeptical Shrug", value: "ヽ(ˇヘˇ)ノ" },
          { name: "Lazy Shrug", value: "┐(￣～￣)┌" },
          { name: "Happy Shrug", value: "┐(︶▽︶)┌" },
          { name: "Casual Confusion", value: "╮(￣～￣)╭" },
          { name: "Classic Shrug", value: "¯\\_(ツ)_/¯" },
          { name: "Tired Shrug", value: "┐( ´ д ` )┌" },
          { name: "Sad Shrug", value: "╮(︶︿︶)╭" },
          { name: "Cheerful Shrug", value: "┐(￣∀￣)┌" },
          { name: "Sleepy Shrug", value: "┐( ˘ ､ ˘ )┌" },
          { name: "Joyful Shrug", value: "╮(︶▽︶)╭" },
          { name: "Relaxed Shrug", value: "╮( ˘ ､ ˘ )╭" },
          { name: "Bored Shrug", value: "┐( ˘_˘ )┌" },
          { name: "Calm Shrug", value: "╮( ˘_˘ )╭" },
          { name: "Excited Shrug", value: "┐(￣ヮ￣)┌" },
          { name: "Energetic Move", value: "ᕕ( ᐛ )ᕗ" },
          { name: "Robot Shrug", value: "┐(シ)┌" }
        ],
      },
      {
        subCategory: 'Confusion',
        description: 'Express bewilderment, uncertainty, and puzzlement with our collection of Confusion kaomojis. These text faces are ideal for when you encounter something that doesn\'t make sense, receive a cryptic message, or are just generally lost. Featuring questioning looks, tilted heads, and symbols like question marks, these kaomojis perfectly capture that feeling of "What?" or "Huh?". Use them to ask for clarification, show that you\'re trying to figure something out, or react to a bizarre situation. They are a fun and clear way to signal that you\'re not following along.',
        kaomojis: [
          { name: "Worried", value: "(￣ω￣;)" },
          { name: "Doubtful", value: "σ(￣、￣〃)" },
          { name: "Unsure", value: "(￣～￣;)" },
          { name: "Anxious", value: "(-_-;)・・・" },
          { name: "Shrug Uncertain", value: "┐('～`;)┌" },
          { name: "Confused Glance", value: "(・_・ヾ" },
          { name: "Embarrassed Confusion", value: "(〃￣ω￣〃ゞ" },
          { name: "Exasperated Shrug", value: "┐(￣ヘ￣;)┌" },
          { name: "Mild Confusion", value: "(・_・;)" },
          { name: "Displeased", value: "(￣_￣)・・・" },
          { name: "Hands Up Confusion", value: "╮(￣ω￣;)╭" },
          { name: "Indifferent", value: "(¯ . ¯;)" },
          { name: "Shocked", value: "(＠_＠)" },
          { name: "Nervous", value: "(・・;)ゞ" },
          { name: "Surprised", value: "Σ(￣。￣ﾉ)" },
          { name: "Puzzled", value: "(・・ ) ?" },
          { name: "Suspicious", value: "(•ิ_•ิ)?" },
          { name: "Wide Eyed", value: "(◎ ◎)ゞ" },
          { name: "Annoyed", value: "(ーー;)" },
          { name: "Disapproving", value: "ლ(ಠ_ಠ ლ)" },
          { name: "Frustrated", value: "ლ(¯ロ¯\"ლ)" },
          { name: "Exasperated 2", value: "(¯ . ¯٥)" },
          { name: "Tired Frustration", value: "(¯ ¯٥)" },
          { name: "Confused Question", value: "(・・?)" },
          { name: "Shocked Eyes", value: "(??_??)" },
          { name: "Surprised Gaze", value: "(⊙.⊙)?" }
        ],
      },
      {
        subCategory: 'Doubt',
        description: 'Show skepticism and uncertainty with our Doubt kaomojis. This selection is perfect for when you\'re not quite convinced by what you\'re seeing or hearing. Featuring suspicious side-eyes, raised eyebrows, and scrutinizing expressions, these text faces allow you to question things without being overly confrontational. Use them to cast a skeptical glance, express your disbelief, or show that you\'re considering something carefully but remain unconvinced. They add a layer of nuance to your conversations, making it clear that you\'re not taking everything at face value.',
        kaomojis: [
          { name: 'Doubtful', value: '(¬_¬")' },
          { name: 'Suspicious', value: '( →_→)' },
          { name: 'Really?', value: '(´-ι_-｀)' },
      { name: 'Hmm', value: '(ー_ー)' },
          { name: 'I see', value: '(⚭_⚭)' },
          { name: 'Not convinced', value: '(´-`*)' },
          { name: 'Peeking', value: ' |･ω･｀)' },
          { name: 'Side Eye', value: '(눈_눈)' },
          { name: 'Watching you', value: '(ಡ_ಡ)☞' },
          { name: 'Observing', value: '(◎ ◎)ゞ' },
          { name: "Suspicious Look", value: "(￢_￢)" },
          { name: "Side Eye", value: "(→_→)" },
          { name: "Doubtful Gaze", value: "(￢ ￢)" },
          { name: "Smirking", value: "(￢‿￢ )" },
          { name: "Skeptical", value: "(¬_¬ )" },
          { name: "Looking Away", value: "(←_←)" },
          { name: "Questioning", value: "(¬ ¬ )" },
          { name: "Playful Smirk", value: "(¬‿¬ )" },
          { name: "Cheeky Look", value: "(↼_↼)" },
          { name: "Confident Side Eye", value: "(⇀_⇀)" },
          { name: "Tired Skeptic", value: "(ᓀ ᓀ)" },
          { name: "Mischievous Smile", value: "(„¬ᴗ¬„)" }
        ],
      },
      {
        subCategory: 'Surprise',
        description: 'Capture moments of astonishment, shock, and awe with our Surprise kaomojis. This category is filled with wide-eyed and open-mouthed expressions perfect for reacting to unexpected events, plot twists, or startling revelations. Whether it\'s a pleasant surprise or a sudden shock, these text faces convey a strong and immediate reaction. Use them when you can\'t believe what just happened, when someone reveals a secret, or when you\'re simply amazed by something. They add a dramatic and expressive element to your messages, ensuring everyone knows just how surprised you are.',
        kaomojis: [
          { name: "Shocked", value: "w(°ｏ°)w" },
          { name: "Astonished", value: "ヽ(°〇°)ﾉ" },
          { name: "Wide Eyes", value: "Σ(O_O)" },
          { name: "Stunned", value: "Σ(°ロ°)" },
          { name: "Eyebrow Raise", value: "(⊙_⊙)" },
          { name: "Confused Look", value: "(o_O)" },
          { name: "Panic Eyes", value: "(O_O;)" },
          { name: "Big Eyes", value: "(O.O)" },
          { name: "Exclamation Shock", value: "(°ロ°) !" },
          { name: "Surprised Question", value: "(o_O) !" },
          { name: "Serious Shock", value: "(□_□)" },
          { name: "Dazed Eyes", value: "Σ(□_□)" },
          { name: "Extreme Surprise", value: "∑(O_O;)" },
          { name: "Horrified", value: "( : ౦ ‸ ౦ : )" 
        ],
      },
    ],
  },
  {
    category: 'Various Actions',
    subCategories: [
      {
        subCategory: 'Greeting',
        description: 'Say hello in style with our Greeting kaomojis. This friendly collection is perfect for starting a conversation, welcoming someone, or just being polite. You\'ll find a variety of welcoming gestures, from a simple wave to a cheerful "Hey there!". These kaomojis are great for opening lines in chats, greeting friends in a group, or just spreading a bit of friendliness. They set a positive and approachable tone right from the start of any interaction, making your digital greetings feel warmer and more personal than just plain text. A great way to make a first impression!',
        kaomojis: [
          { name: "Cheerful Wave", value: "(*・ω・)ﾉ" },
          { name: "Happy Greeting", value: "(￣▽￣)ノ" },
          { name: "Excited Wave", value: "(°▽°)/" },
          { name: "Friendly Wave", value: "( ´ ∀ ` )ﾉ" },
          { name: "Polite Wave", value: "(^-^*)/" },
          { name: "Casual Hello", value: "(＠´ー`)ﾉﾞ" },
          { name: "Shy Wave", value: "(´• ω •`)ﾉ" },
          { name: "Joyful Greeting", value: "( ° ∀ ° )ﾉﾞ" },
          { name: "Energetic Wave", value: "ヾ(*'▽'*)" },
          { name: "Excited Cheer", value: "＼(⌒▽⌒)" },
          { name: "Starry Wave", value: "ヾ(☆▽☆)" },
          { name: "Friendly Salute", value: "( ´ ▽ ` )ﾉ" },
          { name: "Big Smile Wave", value: "(^０^)ノ" },
          { name: "Quick Wave", value: "~ヾ(・ω・)" },
          { name: "Casual Hello 2", value: "(・∀・)ノ" },
          { name: "Happy Wave 2", value: "ヾ(・ω・*)" },
          { name: "Charming Wave", value: "(*°ｰ°)ﾉ" },
          { name: "Simple Wave", value: "(・_・)ノ" },
          { name: "Sweet Greeting", value: "(o´ω`o)ﾉ" },
          { name: "Joyful Wave", value: "( ´ ▽ ` )/" },
          { name: "Calm Wave", value: "(￣ω￣)/" },
          { name: "Gentle Wave", value: "( ´ ω ` )ノﾞ" },
          { name: "Cute Wave", value: "(⌒ω⌒)ﾉ" },
          { name: "Friendly Smile Wave", value: "(o^ ^o)/" },
          { name: "Overjoyed Wave", value: "(≧▽≦)/" },
          { name: "Excited Star Wave", value: "(✧∀✧)/" },
          { name: "Happy Blush Wave", value: "(o´▽`o)ﾉ" },
          { name: "Joyful Greeting 2", value: "(￣▽￣)/" }
        ],
      },
      {
        subCategory: 'Hugging',
        description: 'Send a warm and comforting virtual hug with our Hugging kaomojis. This collection is all about showing affection, support, and closeness. Featuring open arms and embracing figures, these kaomojis are the perfect way to comfort a friend, celebrate a happy moment together, or simply show someone you care. They are incredibly versatile for expressing a wide range of positive emotions, from love and friendship to sympathy and congratulations. When you can\'t be there in person, a hug kaomoji is the next best thing to share a moment of connection.',
        kaomojis: [
          { name: 'Hugging', value: '(づ｡◕‿‿◕｡)づ' },
          { name: 'Come here', value: '(っ´ω`c)' },
          { name: 'Group Hug', value: '( ´∀｀)人(´∀｀ )' },
          { name: 'Warm Hug', value: '（っ・∀・）っ' },
          { name: 'Offering a hug', value: '(づ￣ ³￣)づ' },
          { name: 'I want a hug', value: '⊂(´• ω •`⊂)' },
          { name: 'Tight Hug', value: '╰( ´・ω・)つ──☆' },
          { name: 'Embrace', value: '(ɔˆ ³(ˆ⌣ˆc)' },
          { name: 'Let me hug you', value: '⊂(・﹏・⊂)' },
          { name: 'Big Hug', value: '＼(・ω・)／' },
          { name: "Blowing Hug", value: "(づ￣ ³￣)づ" },
          { name: "Excited Hug", value: "(つ≧▽≦)つ" },
          { name: "Sparkle Hug", value: "(つ✧ω✧)つ" },
          { name: "Cute Hug", value: "(づ ◕‿◕ )づ" },
          { name: "Gentle Hug", value: "(⊃｡•́‿•̀｡)⊃" },
          { name: "Shy Hug", value: "(つ . •́ _ʖ •̀ .)つ" },
          { name: "Mischievous Hug", value: "(っಠ‿ಠ)っ" },
          { name: "Peaceful Hug", value: "(づ◡﹏◡)づ" },
          { name: "Soft Hug", value: "⊂(´• ω •`⊂)" },
          { name: "Playful Hug", value: "⊂(･ω･*⊂)" },
          { name: "Cheerful Hug", value: "⊂(￣▽￣)⊃" },
          { name: "Happy Hug", value: "⊂( ´ ▽ ` )⊃" },
          { name: "Dancing Hug", value: "( ~*-*)~" },
          { name: "Joyful Stretch", value: "(ノ= ⩊ = )ノ" },
          { name: "Warm Hug", value: "(っ ᵔ◡ᵔ)っ" },
          { name: "Cute Face Hug", value: "(っ╹ᆺ╹)っ" }
        ],
      },
      {
        subCategory: 'Winking',
        description: 'Add a touch of playfulness, humor, or flirtation to your messages with our Winking kaomojis. A simple wink can convey a wide range of meanings, from a shared secret and a cheeky joke to a confident "I got this." This collection features a variety of winking faces, each with its own unique personality. They are perfect for lightening the mood, being a little mischievous, or adding a bit of charm to your conversation. A well-placed wink kaomoji can change the entire tone of a message, making it more engaging and fun.',
        kaomojis: [
          { name: 'Wink', value: '(^_-)' },
          { name: 'Cheeky Wink', value: '(^_−)☆' },
          { name: 'Winking Smile', value: '(^.~)' },
          { name: 'Playful Wink', value: '(-_・)' },
          { name: 'Kiss Wink', value: '(~_^) ' },
          { name: 'Subtle Wink', value: '(^_~)' },
          { name: 'Cool Wink', value: '(*^ -^*)' },
          { name: 'Got it', value: '( - wink - )' },
          { name: 'Winking Tongue', value: '(^,＜)' },
          { name: 'You know it', value: '(b^_-) ' },
          { name: "Winking Flirt", value: "(^_~)" },
          { name: "Playful Look", value: "( ﾟｏ⌒)" },
          { name: "Wink and Star", value: "(^_-)≡☆" },
          { name: "Cheeky Smile", value: "(^ω~)" },
          { name: "Excited Wink", value: "(>ω^)" },
          { name: "Praying Wink", value: "(~人^)" },
          { name: "Simple Wink", value: "(^_-)" },
          { name: "Subtle Look", value: "( -_・)" },
          { name: "Flirty Star", value: "(^_<)〜☆" },
          { name: "Shy Wink Star", value: "(^人<)〜☆" },
          { name: "Sparkle Excitement", value: "☆⌒(≧▽​° )" },
          { name: "Playful Sparkle", value: "☆⌒(ゝ。∂)" },
          { name: "Cute Wink", value: "(^_<)" },
          { name: "Star Wink", value: "(^_−)☆" },
          { name: "Cheeky Wink", value: "(･ω<)☆" },
          { name: "Playful Smile Star", value: "(^.~)☆" },
          { name: "Flirty Smile", value: "(^.~)" },
          { name: "Confident Wink", value: "(｡•̀ᴗ-)✧" },
          { name: "Happy Flirt", value: "(>ᴗ•)" },
          { name: "Excited Star Wink", value: "☆(>ᴗ•)" }
        ],
      },
      {
        subCategory: 'Apologizing',
        description: 'Express remorse and sincerity with our Apologizing kaomojis. Saying sorry can be tough, but these text faces can help you convey your message with humility and earnestness. This collection includes kaomojis that are bowing deeply (a sign of apology in Japanese culture), looking regretful, or asking for forgiveness. They are appropriate for both serious apologies and lighthearted "my bad" moments. Using one of these can soften your message and show that you are genuinely sorry, helping to mend misunderstandings and maintain positive relationships.',
        kaomojis: [
          { name: "Respectful Bow", value: "m(_ _)m" },
          { name: "Formal Bow", value: "(シ_ _)シ" },
          { name: "Humble Bow", value: "m(. .)m" },
          { name: "Deep Bow", value: "<(_ _)>" },
          { name: "Polite Bow", value: "人(_ _*)" },
          { name: "Apologetic Bow", value: "(*_ _)人" },
          { name: "Embarrassed Bow", value: "m(_ _;m)" },
          { name: "Sincere Bow", value: "(m;_ _)m" },
          { name: "Sad Bow", value: "(シ. .)シ" }
        ],
      },
      {
        subCategory: 'Nosebleeding',
        description: 'Typically used in anime and manga culture, our Nosebleeding kaomojis represent a comical or exaggerated reaction to seeing something attractive, cute, or overwhelming. It\'s a humorous way to express intense excitement or arousal. This collection features various characters with streams of blood comically gushing from their noses. They are perfect for reacting to a photo of a celebrity crush, a stunning piece of fan art, or an incredibly adorable animal video. It\'s a niche but highly expressive way to say "this is too much for me to handle!" in a funny and culturally savvy way.',
        kaomojis: [
          { name: 'Nosebleed', value: '(´ii｀)' },
          { name: 'Bleeding', value: '(￣ii￣)' },
          { name: 'Fountain', value: '(´ ´ิ OTA ´ิ` )' },
          { name: 'Too cute', value: '(* ´ I ` *)' },
          { name: 'Overwhelmed', value: '(*￣ii￣)' },
          { name: 'Dripping', value: '(＾་།＾)' },
          { name: 'Excited', value: '(;´Д`)ﾊｧﾊｧ' },
          { name: 'Wow', value: '(´p｀)' },
          { name: 'Intense', value: '(〃ω〃)' },
          { name: 'Coughing Blood', value: '( 뿜 )' },
          { name: "Shy Kiss", value: "(*￣ii￣)" },
          { name: "Blushing Kiss", value: "(￣ﾊ￣*)" },
          { name: "Waving Kiss", value: "\\(￣ﾊ￣)" },
          { name: "Cute Shy", value: "(＾་།＾)" },
          { name: "Gentle Smile", value: "(＾〃＾)" },
          { name: "Embarrassed Smile", value: "(￣ ¨ヽ￣)" },
          { name: "Worried Blush", value: "(￣ ;￣)" },
          { name: "Shy Embarrassed", value: "(￣ ;;￣)" }
        ],
      },
      {
        subCategory: 'Hiding',
        description: 'For moments when you want to be discreet, shy, or just plain sneaky, our Hiding kaomojis have you covered. This collection features characters peeking from behind walls, hiding their faces, or trying to disappear into the background. They are perfect for situations where you\'re feeling shy, eavesdropping on a conversation (playfully, of course), or want to make a quiet entrance or exit. These kaomojis add a sense of mystery and fun to your interactions, whether you\'re being a secret observer or just want to be left alone for a bit.',
        kaomojis: [
          { name: "Peeking", value: "|･ω･)" },
          { name: "Peeking Side", value: "ﾍ(･_|" },
          { name: "Waving Peek", value: "|ω･)ﾉ" },
          { name: "Quick Peek", value: "ヾ(･|" },
          { name: "Surprised Peek", value: "|д･)" },
          { name: "Sneaky Smile", value: "|_￣))" },
          { name: "Blushing Peek", value: "|▽//)" },
          { name: "Table Peek 1", value: "┬┴┬┴┤(･_├┬┴┬┴" },
          { name: "Table Peek 2", value: "┬┴┬┴┤･ω･)ﾉ" },
          { name: "Lenny Table Peek", value: "┬┴┬┴┤( ͡° ͜ʖ├┬┴┬┴" },
          { name: "Table Peek 3", value: "┬┴┬┴┤(･_├┬┴┬┴" },
          { name: "Shy Peek", value: "|_・)" },
          { name: "Waving Surprised", value: "|･д･)ﾉ" },
          { name: "Excited Peek", value: "|ʘ‿ʘ)╯" }
        ],
      },
      {
        subCategory: 'Writing',
        description: 'For the studious, the creative, and the busy bees, our Writing kaomojis are perfect for showing you\'re hard at work. This collection features characters that are taking notes, studying, drawing, or typing away. They are ideal for letting your friends know you\'re busy with homework, working on a project, or just in a focused state of mind. Whether you\'re a student hitting the books, a writer battling a deadline, or an artist in the creative zone, these kaomojis visually communicate your dedication and concentration.',
        kaomojis: [
          { name: "Contemplating", value: "__φ(．．)" },
          { name: "Scheming Smile", value: "( ￣ー￣)φ__" },
          { name: "Pondering", value: "__φ(。。)" },
          { name: "Worried Thought", value: "__φ(．．;)" },
          { name: "Determined Planning", value: "ヾ( `ー´)シφ__" },
          { name: "Writing Note", value: "__〆(￣ー￣ )" },
          { name: "Casual Thought", value: "....φ(・∀・*)" },
          { name: "Focused Thinking", value: "___〆(・∀・)" },
          { name: "Cheerful Planning", value: "( ^▽^)ψ__" },
          { name: "Happy Note", value: "....φ(︶▽︶)φ...." },
          { name: "Simple Ponder", value: "( . .)φ__" },
          { name: "Studying Carefully", value: "__φ(◎◎ヘ)" }
        ],
      },
      {
        subCategory: 'Running',
        description: 'Express a sense of urgency, escape, or excitement with our Running kaomojis. This dynamic collection is filled with characters on the move. Whether you\'re rushing to an appointment, playfully running away from a situation, or charging towards a goal, these text faces add action and energy to your messages. They are perfect for saying "I\'m on my way!", "Gotta go!", or for depicting a chase. The sense of motion in these kaomojis makes your text feel more alive and immediate, conveying speed and purpose in a fun, visual way.',
        kaomojis: [
          { name: 'Running', value: 'ε=ε=┌( >_<)┘' },
          { name: 'Dashing', value: 'C= C= C= ┌(;・ω・)┘' },
          { name: 'Fleeing', value: '((( つ•̀ω•́)つ' },
          { name: 'Hurrying', value: '─=≡Σ((( つ•̀ω•́)つ' },
      { name: 'Running away', value: 'ε=ε=┌( ´Д`)┘' },
          { name: 'Chasing', value: '=͟͟͞͞( っ`´)っ' },
          { name: 'On my way!', value: 'ﾀﾀﾀｯ!!≡≡≡ﾍ(*-ω-)ﾉ' },
          { name: 'Gotta go', value: 'ε=(/`・ω・´)/' },
          { name: 'Full speed', value: '─=≡Σᕕ( ᐛ )ᕗ' },
          { name: 'Escape', value: 'ε=ε=ε=ε=┌(;￣◇￣)┘' },
          { name: "Running Excitedly", value: "☆ﾐ(o*･ω･)ﾉ" },
          { name: "Sprint Forward", value: "C= C= C= C= C=┌(;・ω・)┘" },
          { name: "Frantic Escape", value: "─=≡Σ((( つ＞＜)つ" },
          { name: "Dash Quickly", value: "ε=ε=ε=ε=┌(;￣▽￣)┘" },
          { name: "Panicked Run", value: "ε=ε=┌( >_<)┘" },
          { name: "Angry Charge", value: "C= C= C= C=┌( `ー´)┘" },
          { name: "Joyful Leap", value: "ε===(っ≧ω≦)っ" },
          { name: "Desperate Flee", value: "ヽ(￣д￣;)ノ=3=3=3" },
          { name: "Frustrated Escape", value: "。。。ミヽ(。＞＜)ノ" }
        ],
      },
      {
        subCategory: 'Sleeping',
        description: 'Signal that it\'s time for rest or that you\'re feeling tired with our Sleeping kaomojis. This cozy collection is perfect for ending a late-night conversation, complaining about being sleepy during the day, or just dreaming of your bed. Featuring closed eyes, "zzz" symbols, and sometimes even drool, these kaomojis perfectly capture the state of being asleep or drowsy. They are a universal and cute way to say "good night" or to express your current low-energy state to friends and family. Let them know it\'s time to recharge.',
        kaomojis: [
          { name: 'Sleeping', value: '(ᵕ.ᵕ)' },
          { name: 'Dozing off', value: '(－_－) zzZ' },
          { name: 'Sleepy', value: '(´-ω-`)' },
          { name: 'Good night', value: 'おやすみ' },
          { name: 'In bed', value: '...(_ _).｡o○' },
          { name: 'Dreaming', value: '(∪｡∪)｡｡｡zzz' },
          { name: 'Napping', value: '(-ω-ゞ' },
          { name: 'Tired', value: '(=-ω-)zzZ' },
          { name: 'Knocked out', value: '_(´ཀ`」 ∠)_' },
          { name: 'Lying Down', value: '_(」∠ ､ﾝ､)_'},
          { name: "Sleeping Peacefully", value: "[(－－)]..zzZ" },
          { name: "Drowsy", value: "(－_－) zzZ" },
          { name: "Snuggly Sleep", value: "(∪｡∪)｡｡｡zzZ" },
          { name: "Calm Nap", value: "(－ω－) zzZ" },
          { name: "Deep Sleep", value: "(￣o￣) zzZZzzZZ" },
          { name: "Resting Quietly", value: "(( _ _ ))..zzzZZ" },
          { name: "Sleeping Soundly", value: "(￣ρ￣)..zzZZ" },
          { name: "Peaceful Snooze", value: "(－.－)...zzz" },
          { name: "Comfy Rest", value: "(＿ ＿*) Z z z" },
          { name: "Knocked Out", value: "(x . x) ~~zzZ" }
        ],
      },
    ],
  },
  {
    category: 'Animals',
    subCategories: [
      {
        subCategory: 'Cat',
        description: 'Enter the charming and mischievous world of felines with our Cat kaomojis. This extensive collection captures all facets of a cat\'s personality, from cute and cuddly to aloof and sassy. You\'ll find cats playing, sleeping, demanding attention, and showing off their classic pointy ears and whiskers. These are perfect for any cat lover to express their current mood or to react to anything cute online. They are one of the most popular and versatile types of kaomoji, adding a touch of "kawaii" and playful energy to any conversation.',
        kaomojis: [
          { name: 'Cat', value: '(=^･ω･^=)' },
          { name: 'Meow', value: '（Φ ω Φ）' },
          { name: 'Kitten', value: '(=´∀｀)' },
          { name: 'Grumpy Cat', value: '(=｀ェ´=)' },
          { name: 'Hiding Cat', value: '（=￣o￣=）' },
          { name: 'Stretching Cat', value: '(=ＴェＴ=)' },
          { name: 'Fat Cat', value: '（´・ω・`）' },
          { name: 'Peeking Cat', value: '｜･ω･)' },
          { name: 'Playing Cat', value: 'ヽ(=^･ω･^=)丿' },
          { name: 'Sleeping Cat', value: '(=-ω-)zzZ' },
          { name: "Cute Cat Face", value: "(=^･ω･^=)" },
          { name: "Happy Cat", value: "(=^･ｪ･^=)" },
          { name: "Playful Cat", value: "(=①ω①=)" },
          { name: "Nyaa Cat", value: "( =ω=)..nyaa" },
          { name: "Sad Cat", value: "(= ; ｪ ; =)" },
          { name: "Angry Cat", value: "(=`ω´=)" },
          { name: "Smiling Cat", value: "(=^‥^=)" },
          { name: "Shy Cat", value: "( =ノωヽ=)" },
          { name: "Cheerful Cat", value: "(=⌒‿‿⌒=)" },
          { name: "Sweet Cat", value: "(=^ ◡ ^=)" },
          { name: "Relaxed Cat", value: "(=^-ω-^=)" },
          { name: "Excited Cat", value: "ヾ(=`ω´=)ノ”" },
          { name: "Soft Cat", value: "(＾• ω •＾)" },
          { name: "Jumping Cat", value: "(/ =ω=)/" },
          { name: "Flower Cat", value: "ฅ(•ㅅ•❀)ฅ" },
          { name: "Shy Kitty", value: "ฅ(• ɪ •)ฅ" },
          { name: "Relaxed Kitty", value: "ଲ(ⓛ ω ⓛ)ଲ" },
          { name: "Happy Bear-Cat", value: "(^=◕ᴥ◕=^)" },
          { name: "Calm Cat", value: "( =ω= )" },
          { name: "Blushing Cat", value: "(^˵◕ω◕˵^)" },
          { name: "Gentle Bear-Cat", value: "(^◔ᴥ◔^)" },
          { name: "Joyful Bear-Cat", value: "(^◕ᴥ◕^)" },
          { name: "Excited Kitty", value: "ต(=ω=)ต" },
          { name: "Fluffy Cat", value: "( Φ ω Φ )" },
          { name: "Happy Kitty 2", value: "ฅ(^◕ᴥ◕^)ฅ" }
        ],
      },
      {
        subCategory: 'Bear',
        description: 'Embrace the cute and cuddly nature of our Bear kaomojis. This collection features a variety of bear faces, known for their distinct `(エ)` shaped mouths. These kaomojis can be used to express a range of emotions, from happy and content to sad or angry, all with an underlying sense of adorable chunkiness. They are great for conveying a friendly and approachable vibe. Whether you want to be a fierce grizzly or a gentle teddy bear, these kaomojis offer a unique and lovable way to express yourself in text.',
        kaomojis: [
          { name: 'Bear', value: '(´(エ)｀)' },
          { name: 'Happy Bear', value: 'ヽ(´(ｴ)｀)ﾉ' },
          { name: 'Angry Bear', value: '(╬ ´(エ)｀)' },
          { name: 'Sad Bear', value: '(´(エ)｀)' },
          { name: 'Dancing Bear', value: 'ʕ•ᴥ•ʔ' },
          { name: 'Shy Bear', value: '(〃(ｴ)〃)' },
          { name: 'Waving Bear', value: '(´(エ)｀)ﾉ' },
          { name: 'Confused Bear', value: '／(･ × ･)＼' },
          { name: 'Panda', value: '(´･(ｴ)･｀)' },
          { name: 'Polar Bear', value: '⊂(・(ェ)・)⊃' },
          { name: "Sad Bear", value: "( ´(ｴ)ˋ )" },
          { name: "Relaxed Bear", value: "(*￣(ｴ)￣*)" },
          { name: "Cheerful Bear", value: "ヽ(￣(ｴ)￣)ﾉ" },
          { name: "Waving Bear", value: "(／￣(ｴ)￣)／" },
          { name: "Neutral Bear", value: "(￣(ｴ)￣)" },
          { name: "Excited Bear", value: "ヽ( ˋ(ｴ)´ )ﾉ" },
          { name: "Hugging Bear", value: "⊂(￣(ｴ)￣)⊃" },
          { name: "Shy Bear", value: "(／(ｴ)＼)" },
          { name: "Hugging Baby Bear", value: "⊂(´(ェ)ˋ)⊃" },
          { name: "Sad Arms Up Bear", value: "(/-(ｴ)-＼)" },
          { name: "Surprised Bear", value: "(/°(ｴ)°)/" },
          { name: "Happy Panda", value: "ʕ ᵔᴥᵔ ʔ" },
          { name: "Calm Panda", value: "ʕ •ᴥ• ʔ" },
          { name: "Determined Bear", value: "ʕ •̀ ω •́ ʔ" },
          { name: "Shouting Bear", value: "ʕ •̀ o •́ ʔ" },
          { name: "Angry Bear", value: "ʕಠᴥಠʔ" }
        ],
      },
      {
        subCategory: 'Dog',
        description: 'Celebrate man\'s best friend with our collection of Dog kaomojis. These text faces are full of the loyalty, energy, and goofy charm that we love about dogs. Featuring floppy ears, wagging tails, and happy panting faces, this category is perfect for dog lovers to share their enthusiasm. Use them to show excitement, loyalty, or just to be plain silly and friendly. From a loyal retriever to a tiny yapping chihuahua, these kaomojis capture the diverse and lovable spirit of dogs, bringing a burst of positive energy to your chats.',
        kaomojis: [
          { name: 'Dog', value: 'V=(° °)=V' },
          { name: 'Puppy', value: '(●´ω｀●)' },
          { name: 'Woof', value: 'U・ᴥ・U' },
          { name: 'Happy Dog', value: '∪･ω･∪' },
          { name: 'Sad Puppy', value: '(•́ι_•̀*)' },
          { name: 'Shiba Inu', value: '(＾・(ェ)・＾)' },
          { name: 'Poodle', value: '@(o･ｪ･o)@' },
          { name: 'Wagging Tail', value: 'Uo･ｪ･oU' },
          { name: 'Good boy', value: '(υ´Д`)' },
          { name: 'Bark', value: '(U・x・U)' },
          { name: "Happy Dog", value: "∪＾ェ＾∪" },
          { name: "Curious Dog", value: "∪･ω･∪" },
          { name: "Sleepy Dog", value: "∪￣-￣∪" },
          { name: "Shy Dog", value: "∪･ｪ･∪" },
          { name: "Angry Dog", value: "Ｕ^皿^Ｕ" },
          { name: "Sad Dog", value: "ＵＴｪＴＵ" },
          { name: "Cheerful Dog", value: "U^ｪ^U" },
          { name: "Happy Puppy", value: "V●ᴥ●V" },
          { name: "Calm Dog", value: "U・ᴥ・U" }
        ],
      },
      {
        subCategory: 'Rabbit',
        description: 'Hop into cuteness with our Rabbit kaomojis. Known for their long ears and twitching noses, these text faces are perfect for conveying a sense of innocence, shyness, or gentle charm. The `x` character is often used to represent their distinctive mouths. This collection features rabbits in various moods, from happy and energetic to quiet and thoughtful. They are a great choice when you want to appear cute, harmless, and friendly. Let these adorable bunnies add a soft and sweet touch to your messages.',
        kaomojis: [
          { name: 'Rabbit', value: '（・ｘ・）' },
          { name: 'Bunny', value: 'o(・x・)' },
          { name: 'Hopping', value: '／(・x・)＼' },
          { name: 'Sad Rabbit', value: '(´x`)' },
          { name: 'Cute Bunny', value: '（´・x・`）' },
          { name: 'Miffy', value: '(x . x)' },
          { name: 'Waving Rabbit', value: '(・x・)ﾉ' },
          { name: 'Long Ears', value: 'u(・x・)u' },
          { name: 'Eating', value: '냠냠(・×・)' },
          { name: 'Sleeping Rabbit', value: '(- x -)' },
          { name: "Frustrated Face 1", value: "／(≧ x ≦)＼" },
          { name: "Upset Face 2", value: "／(･ × ･)＼" },
          { name: "Sad Face 1", value: "／(=´x`=)＼" },
          { name: "Embarrassed Face", value: "／(^ x ^)＼" },
          { name: "Confused Cat Face", value: "／(=･ x ･=)＼" },
          { name: "Shy Cat Face", value: "／(^ × ^)＼" },
          { name: "Angry Face", value: "／(＞×＜)＼" },
          { name: "Crying Face", value: "／(˃ᆺ˂)＼" },
          { name: "Joyful Paw", value: "૮ ˶ᵔ ᵕ ᵔ˶ ა" },
          { name: "Happy Paw", value: "૮₍ ˶• ༝ •˶ ₎ა" }
        ],
      },
      {
        subCategory: 'Pig',
        description: 'Oink your way into conversations with our charming Pig kaomojis. These text faces are easily recognizable by their snout-like `(oo)` or `(ブ)` characters. They can be used to represent cuteness, a love for food, or just a bit of silly fun. While sometimes used to imply greed or laziness in a playful manner, they are most often just cute and chubby characters. This collection offers a variety of piggy expressions, perfect for when you want to add a unique and amusing animal to your digital farm.',
        kaomojis: [
          { name: 'Pig', value: '(´・(oo)・｀)' },
          { name: 'Oink', value: '(ブ)' },
          { name: 'Happy Pig', value: '(*´(oo)`)' },
          { name: 'Snout', value: '(´(00)｀)' },
          { name: 'Piglet', value: 'ヽ( ´(oo)｀)ﾉ' },
          { name: 'Sad Pig', value: '(´(oo)｀)' },
          { name: 'Angry Pig', value: '（｀（●●）´）' },
          { name: 'Running Pig', value: 'ε＝(＞(OO)＜) ' },
          { name: 'Chubby Pig', value: '(`(エ)´)ﾉ' },
          { name: 'Winking Pig', value: '(^ (oo) ^)' },
          { name: "Sad Pig", value: "( ´(00)ˋ )" },
          { name: "Relaxed Pig", value: "(￣(ω)￣)" },
          { name: "Excited Pig", value: "ヽ( ˋ(00)´ )ノ" },
          { name: "Cute Pig", value: "( ´(oo)ˋ )" },
          { name: "Joyful Pig", value: "＼(￣(oo)￣)／" },
          { name: "Crying Pig", value: "｡ﾟ(ﾟ´(00)`ﾟ)ﾟ｡" },
          { name: "Neutral Pig", value: "(￣(00)￣)" },
          { name: "Happy Pig", value: "(ˆ(oo)ˆ)" }
        ],
      },
      {
        subCategory: 'Bird',
        description: 'Let your messages take flight with our collection of Bird kaomojis. These text faces often use the `θ` or `⊝` characters to represent a beak, giving them a distinct and adorable look. This category includes everything from tiny chirping chicks to majestic owls. They can be used to represent freedom, nature, or to convey a cute and delicate presence. Whether you\'re an early bird sending a morning greeting or a night owl staying up late, you\'ll find a feathered friend here to express your mood.',
        kaomojis: [
          { name: 'Bird', value: '（・⊝・）' },
          { name: 'Chick', value: '(・θ・)' },
          { name: 'Owl', value: '(・o・)' },
          { name: 'Penguin', value: '（＾🐧＾）' },
          { name: 'Flying Bird', value: 'ε( ・ө・)з' },
          { name: 'Chirping', value: 'ピヨピヨ' },
          { name: 'Angry Bird', value: '(`･⊝･´)' },
          { name: 'Small Bird', value: 'ヽ( ´θ｀)ノ' },
          { name: 'Pecking', value: 'つつく' },
          { name: 'Flapping Wings', value: '＼(・o・)／' },
          { name: "Sleepy Bird", value: "(￣Θ￣)" },
          { name: "Determined Bird", value: "(`･Θ･´)" },
          { name: "Serious Bird", value: "( ˋ Θ ´ )" },
          { name: "Surprised Bird", value: "(◉Θ◉)" },
          { name: "Excited Bird", value: "＼( ˋ Θ ´ )／" },
          { name: "Curious Bird", value: "(･θ･)" },
          { name: "Calm Bird", value: "(・Θ・)" },
          { name: "Shouting Bird", value: "ヾ(￣◇￣)ノ〃" },
          { name: "Neutral Bird", value: "(･Θ･)" }
        ],
      },
      {
        subCategory: 'Fish',
        description: 'Dive deep into the ocean of expression with our Fish kaomojis. These aquatic text faces are perfect for anything water-related, or just for adding a quirky and unique character to your conversations. They are often created using angle brackets for the body and various symbols for eyes and fins. This collection features schools of fish, solitary swimmers, and even the occasional intimidating shark. Use them to say you\'re "just keep swimming," to talk about a beach trip, or simply to be a little different from the usual animal kaomojis.',
        kaomojis: [
          { name: 'Fish', value: '<・)))><<' },
          { name: 'Swimming', value: '＞°）mニニニニ＝～' },
          { name: 'Shark', value: '(lll-ω-)' },
          { name: 'School of Fish', value: '＜コ：ミ' },
          { name: 'Small Fish', value: 'ϵ( ‘Θ’ )϶' },
          { name: 'Big Fish', value: 'くコ:彡' },
          { name: 'Glub glub', value: '○o。' },
          { name: 'Pufferfish', value: '🐡' },
          { name: 'Fishy Kiss', value: '<*)>>>=<' },
          { name: 'Korean Fish', value: '물고기' },
          { name: "Swimming Fish 1", value: "(°)#))<<" },
          { name: "Swimming Fish 2", value: "<・ )))><<" },
          { name: "Fast Fish", value: "ζ°)))彡" },
          { name: "Jumping Fish", value: ">°))))彡" },
          { name: "Swimming Fish 3", value: "(°))<<" },
          { name: "Playful Fish", value: ">^)))<～～" },
          { name: "Angry Fish", value: "≧( ° ° )≦" }
        ],
      },
      {
        subCategory: 'Spider',
        description: 'Creep into your chats with our Spider kaomojis. While they might be spooky for some, these multi-legged text faces can also be used in a cute or playful way. They are intricately designed using various characters to form their bodies and many legs. This collection is perfect for Halloween messages, talking about something creepy, or for fans of a certain web-slinging superhero. Whether you want to be a little bit scary or surprisingly adorable, these spider kaomojis are sure to make an impression and stand out in any conversation.',
        kaomojis: [
          { name: 'Spider', value: '/╲/\\╭(ರರ⌓రర)╮/\\╱\\' },
          { name: 'Web', value: '🕸️' },
          { name: "Scary Spider", value: "/╲/\\╭( O_O )╮/\\╱\\" },
          { name: 'Cute Spider', value: '/////////' },
          { name: 'Hanging Spider', value: '...((φ(．．。)φ)))...' },
          { name: 'Tiny Spider', value: '(ሸ)' },
          { name: 'Spider Legs', value: '(( Pública ))' },
          { name: 'Jumping Spider', value: '(/) (°,,°) (/)' },
          { name: 'Crawling', value: '... crawling ...' },
          { name: 'Spooky', value: '... spooky ...' },
          { name: "Angry Monster 1", value: "/╲/\\╭(ఠఠ益ఠఠ)╮/\\╱\\" },
          { name: "Angry Monster 2", value: "/╲/\\╭(ರರ⌓ರರ)╮/\\╱\\" },
          { name: "Furious Demon", value: "/╲/\\╭༼ ººل͟ºº ༽╮/\\╱\\" },
          { name: "Lenny Rage", value: "/╲/\\╭( ͡°͡° ͜ʖ ͡°͡°)╮/\\╱\\" },
          { name: "Crazy Eyes", value: "/╲/\\╭[ ᴼᴼ ౪ ᴼᴼ]╮/\\╱\\" },
          { name: "Determined Fighter", value: "/╲/\\( •̀ ω •́ )/\\╱\\" },
          { name: "Panicked Monster", value: "/╲/\\╭[☉﹏☉]╮/\\╱\\" }
        ],
      },
    ],
  },
  {
    category: 'Other Types',
    subCategories: [
      {
        subCategory: 'Friends',
        description: 'Celebrate the joy of companionship with our Friends kaomojis. This heartwarming collection is all about showing camaraderie, teamwork, and the special bond between friends. You\'ll find kaomojis holding hands, cheering each other on, and sharing happy moments together. They are perfect for group chats, expressing appreciation for your buddies, or talking about a fun activity you did together. These text faces radiate positive and supportive vibes, making them a wonderful way to reinforce your friendships in the digital world.',
        kaomojis: [
          { name: 'Friends', value: '( ´∀｀)人(´∀｀ )' },
          { name: 'Besties', value: '(*・ω・)人(・ω・*)' },
          { name: 'Cheers!', value: '( ´∀｀)っ凵☆凵c(´∀｀ )' },
          { name: 'High Five', value: '（・ω・）人（・ω・）' },
          { name: 'Teamwork', value: 'o(・ω・o)=з=з(o・ω・)o' },
          { name: 'Let\'s go!', value: '＼(・ω・)／' },
          { name: 'Shoulder to Shoulder', value: '(肩を組む)' },
          { name: 'Good Friends', value: '(´ω｀*)人(*´ω｀)' },
          { name: 'Huddle', value: '(((´・ω・)っ' },
          { name: 'You and Me', value: '☆(・ω・)人(・ω・)☆' },
          { name: "High Five 1", value: "ヾ(・ω・)メ(・ω・)ノ" },
          { name: "Cheerful Duo", value: "ヽ(∀° )人( °∀)ノ" },
          { name: "Happy Pair", value: "ヽ( ⌒o⌒)人(⌒-⌒ )ﾉ" },
          { name: "Joyful Trio", value: "(*^ω^)八(⌒▽⌒)八(-‿‿- )ヽ" },
          { name: "Excited Friends", value: "＼(＾∀＾)メ(＾∀＾)ノ" },
          { name: "Celebrating Together", value: "ヾ(￣ー￣(≧ω≦*)ゝ" },
          { name: "Cat & Friend", value: "ヽ( ⌒ω⌒)人(=^‥^= )ﾉ" },
          { name: "Happy Buddies", value: "ヽ(≧◡≦)八(o^ ^o)ノ" },
          { name: "Fun Duo", value: "(*・∀・)爻(・∀・*)" },
          { name: "Magical Friendship", value: "｡*:☆(・ω・人・ω・)｡:゜☆｡" },
          { name: "Group Cheer", value: "o(^^o)(o^^o)(o^^o)(o^^)o" },
          { name: "Chain of Joy", value: "(((￣(￣(￣▽￣)￣)￣)))" },
          { name: "Complex Happiness", value: "(°(°ω(°ω°(☆ω☆)°ω°)ω°)°)" },
          { name: "Mixed Emotions", value: "ヾ(・ω・`)ノヾ(´・ω・)ノ゛" },
          { name: "Playful Spirits", value: "Ψ( `∀)(∀´ )Ψ" },
          { name: "Rolling Joy", value: "(っ˘▽˘)(˘▽˘)˘▽˘ς)" },
          { name: "Excited Cluster", value: "(((*°▽°*)八(*°▽°*)))" },
          { name: "Dual Greeting", value: "☆ヾ(*´・∀・)ﾉヾ(・∀・`*)ﾉ☆" },
          { name: "Mutual Smile", value: "(*＾ω＾)人(＾ω＾*)" },
          { name: "Joyful Pair 2", value: "٩(๑･ิᴗ･ิ)۶٩(･ิᴗ･ิ๑)۶" },
          { name: "Pointing Friends", value: "(☞°ヮ°)☞ ☜(°ヮ°☜)" },
          { name: "Triple Cheer", value: "＼(▽￣ \\ (￣▽￣) / ￣▽)／" },
          { name: "Mirrored Joy", value: "\\( ˙▿˙ )/\\( ˙▿˙ )/" }
        ],
      },
      {
        subCategory: 'Enemies',
        description: 'Depict conflict and rivalry with our Enemies kaomojis. This collection is for those moments of playful banter, competitive spirit, or genuine dislike. Featuring kaomojis fighting, glaring at each other, and showing clear opposition, these text faces are perfect for talking about sports rivals, debating with a friend, or role-playing a confrontation. While they can represent genuine anger, they are most often used in a humorous or exaggerated way to add some drama and action to a conversation. Let the battle of text faces begin!',
        kaomojis: [
          { name: 'Fighting', value: '(ง’̀-‘́)ง' },
          { name: 'Punch', value: '(o` ´o)' },
          { name: 'Versus', value: 'VS' },
          { name: 'Glare', value: '( ` ω ´ )' },
          { name: 'Stare down', value: '( ` ・´)爻(｀・ ´ )' },
          { name: 'Duel', value: '(＃`Д´)⊃-o-o⊂(・ω・´)' },
          { name: 'You vs Me', value: '(ಠ_ಠ)┌∩┐' },
          { name: 'Rivalry', value: '(メ▼▼)人(▼▼メ)' },
          { name: 'Conflict', value: '(-_(-_(-_(-_-)_-)-_-)-_-)' },
          { name: 'Get ready to fight', value: '୧༼ಠ益ಠ༽୨' },
          { name: "Magic Attack 1", value: "ヽ( ･∀･)ﾉ_θ彡☆Σ(ノ `Д´)ノ" },
          { name: "Throwing Star", value: "(*´∇`)┌θ☆(ﾉ>_<)ﾉ" },
          { name: "Swinging Weapon", value: "( ￣ω￣)ノﾞ⌒☆ﾐ(o _ _)o" },
          { name: "Angry Spell", value: "(*`0´)θ☆(メ°皿°)ﾉ" },
          { name: "Sneaky Attack", value: "(o¬‿¬o )...☆ﾐ(*x_x)" },
          { name: "Rage Strike", value: "(╬￣皿￣)=○＃(￣#)３￣)" },
          { name: "Long Shot", value: "(; -_-)――――――C<―_-)" },
          { name: "Chain Attack", value: "＜( ￣︿￣)︵θ︵θ︵☆(＞口＜－)" },
          { name: "Punch Combo", value: "(￣ε(#￣)☆╰╮o(￣▽￣///)" },
          { name: "Rapid Fire 1", value: "ヽ(>_<ヽ) ―⊂|=0ヘ(^‿^ )" },
          { name: "Rapid Fire 2", value: "ヘ(>_<ヘ) ￢o(￣‿￣ﾒ)" },
          { name: "Multi Strike", value: ",,((( ￣□)_／ ＼_(○￣ ))),," },
          { name: "Gun Fire 1", value: "(҂` ﾛ ´)︻デ═一" },
          { name: "Gun Fire 2", value: "＼(º □ º l|l)/" },
          { name: "Table Flip Attack", value: "(╯°Д°)╯︵ /(.□ . ＼)" },
          { name: "Double Smash", value: "(¬_¬'')ԅ(￣ε￣ԅ)" },
          { name: "Monster Smash", value: "/( .□.)＼ ︵╰(°益°)╯︵ /(.□. /)" },
          { name: "Explosion Strike", value: "(ﾉ-.-)ﾉ….((((((((((((●~* ( >_<)" },
          { name: "Power Throw", value: "!!(ﾒ￣ ￣)_θ☆°0°)/" },
          { name: "Special Attack 1", value: "(`⌒*)O-(`⌒´Q)" },
          { name: "Power Combo", value: "(((ง’ω’)و三 ง’ω’)ڡ≡　☆⌒ﾐ((x_x)" },
          { name: "Fist Attack", value: "(งಠ_ಠ)ง　σ( •̀ ω •́ σ)" },
          { name: "Magic Blast", value: "(っ•﹏•)っ ✴==≡눈٩(`皿´҂)ง" },
          { name: "Cheerful Spell", value: "(｢• ω •)｢ (⌒ω⌒`)" },
          { name: "Healing Magic", value: "( °ᴗ°)~ð (/❛o❛\\)" }
        ],
      },
      {
        subCategory: 'Weapons',
        description: 'Arm yourself with expression using our Weapon kaomojis. This collection features characters wielding a variety of items, from swords and guns to more comical weapons like frying pans. They are most often used in a playful, non-threatening context to add drama or humor. Use them to declare a friendly challenge, to show you mean business (in a joking way), or to add action to a story. Whether you\'re a noble knight with a sword or a secret agent with a pistol, these kaomojis let you bring some action-packed fun to your chats.',
        kaomojis: [
          { name: 'Sword', value: '( ` ω ´ )' },
          { name: 'Gun', value: '(・∀・)・∀・)・∀・)・∀・)・∀・)⌐■-■' },
          { name: 'Knife', value: '(＾ω＾)🔪' },
          { name: 'Bow and Arrow', value: '🏹' },
          { name: 'Bomb', value: '( ・ω・)っ💣' },
          { name: 'Laser Beam', value: '(σ・∀・)σ' },
          { name: 'Magic Wand', value: '(∩^o^)⊃━☆ﾟ.*･｡' },
          { name: 'Bat', value: '(メ` ´)ノ' },
          { name: 'Frying Pan', value: '🍳' },
          { name: 'Pointing Gun', value: '( 빵야 )' },
          { name: "Star Throw", value: "( ・∀・)・・・--------☆" },
          { name: "Arrow Shot", value: "(/-_・)/D・・・・・------ →" },
          { name: "Punch Attack", value: "(^ω^)ノﾞ(((((((((●～*" },
          { name: "Fortune Spell", value: "( -ω-)／占~~~~~" },
          { name: "Energy Throw", value: "(/・・)ノ　　 (( く ((へ" },
          { name: "Rapid Strike", value: "―⊂|=0ヘ(^^ )" },
          { name: "Infinite Spin", value: "○∞∞∞∞ヽ(^ー^ )" },
          { name: "Long Shot", value: "(; ・_・)――――C" },
          { name: "Gun Blast", value: "(ಠ o ಠ)¤=[]:::::>" },
          { name: "Magic Spray", value: "(*＾＾)/~~~~~~~~~~◎" },
          { name: "Angry Punch", value: "￢o(￣-￣ﾒ)" },
          { name: "Crying Strike", value: "―(T_T)→" },
          { name: "Falling Smash", value: "((( ￣□)_／" },
          { name: "Gun Fire", value: "(ﾒ` ﾛ ´)︻デ═一" },
          { name: "Table Flip Attack", value: "( ´-ω･)︻┻┳══━一" },
          { name: "Gun Combo", value: "(ﾒ￣▽￣)︻┳═一" },
          { name: "Magic Blast", value: "✴==≡눈٩(`皿´҂)ง" },
          { name: "Special Strike", value: "Q(`⌒´Q)" }
        ],
      },
      {
        subCategory: 'Magic',
        description: 'Add a sprinkle of enchantment and wonder to your conversations with our Magic kaomojis. This mystical collection features wizards casting spells, magical girls transforming, and other fantastical elements. They are perfect for expressing a sense of awe, making a wish, or talking about anything related to fantasy and magic. Whether you\'re trying to summon good luck, celebrate a magical moment, or just love the idea of casting spells, these kaomojis bring a touch of the extraordinary to the everyday digital world.',
        kaomojis: [
          { name: 'Casting Spell', value: '(∩^o^)⊃━☆ﾟ.*･｡' },
          { name: 'Magic', value: '(*･ω･)ﾉ' },
          { name: 'Sparkles', value: 'キラキラ' },
          { name: 'Wish', value: '(人◕ω◕)' },
          { name: 'Wizard', value: 'ヾ(＠⌒ー⌒＠)ノ' },
          { name: 'Summoning', value: '༼ つ ◕_◕ ༽つ' },
          { name: 'Poof!', value: '뿅' },
          { name: 'Enchanting', value: '(~˘▾˘)~' },
          { name: 'Magical Girl', value: '(*°∀°)=3' },
          { name: 'Abra Kadabra', value: '(ノ´ヮ´)ﾉ*:･ﾟ✧' },
          { name: "Chain Magic", value: "(ノ ˘_˘)ノ　ζ|||ζ　ζ|||ζ　ζ|||ζ" },
          { name: "Shooting Star", value: "(ﾉ≧∀≦)ﾉ ‥…━━━★" },
          { name: "Sparkling Blast", value: "(ﾉ>ω<)ﾉ :｡･:*:･ﾟ’★,｡･:*:･ﾟ’☆" },
          { name: "Celebration Magic", value: "(ノ°∀°)ノ⌒･*:.｡. .｡.:*･゜ﾟ･*☆" },
          { name: "Lenny Spell", value: "╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ" },
          { name: "Angry Magic", value: "(＃￣□￣)o━∈・・━━━━☆" },
          { name: "Flower Blast", value: "(⊃｡•́‿•̀｡)⊃━✿✿✿✿✿✿" },
          { name: "Starburst", value: "(∩ᄑ_ᄑ)⊃━☆ﾟ*･｡*･:≡( ε:)" },
          { name: "Magic Throw", value: "(/￣ー￣)/~~☆’.･.･:★’.･.･:☆" },
          { name: "Flame Throw", value: "(∩` ﾛ ´)⊃━炎炎炎炎炎" }
        ],
      },
      {
        subCategory: 'Food',
        description: 'Share your love for all things delicious with our Food kaomojis. This tasty collection is for the foodies, the snack lovers, and anyone who is feeling a bit hungry. You\'ll find kaomojis enjoying a meal, drinking a beverage, or just dreaming about their next snack. They are perfect for talking about dinner plans, reacting to a picture of a delicious dish, or letting your friends know it\'s time for a coffee break. These text faces make conversations about food even more fun and appetizing.',
        kaomojis: [
          { name: 'Eating', value: '( ´З｀)＝３' },
          { name: 'Drinking', value: '( ´∀｀)っ凵☆凵c(´∀｀ )' },
          { name: 'Yummy', value: '（＾～＾）' },
          { name: 'Full', value: '(*´∀｀*)' },
          { name: 'Coffee', value: '( ´ー｀)y-~~☕' },
          { name: 'Tea', value: '🍵' },
          { name: 'Onigiri', value: '🍙' },
          { name: 'Bento', value: '[弁当]' },
          { name: 'Cheers!', value: '乾杯！' },
          { name: 'Hungry', value: 'ԅ( `ิิ ∇ `ิิ ԅ)' },
          { name: "Eating Snack", value: "(っ˘ڡ˘ς)" },
          { name: "Pouring Drink", value: "( o˘◡˘o) ┌iii┐" },
          { name: "Serving Tea", value: "(　’ω’)旦~~" },
          { name: "Hot Spring Drink", value: "( ˘▽˘)っ♨" },
          { name: "Steam Drink", value: "♨o(>_<)o♨" },
          { name: "Pouring Soup", value: "( ・ω・)o-{{[〃]}}" },
          { name: "Serving Dish 1", value: "(　・ω・)⊃-[二二]" },
          { name: "Serving Dish 2", value: "( ・・)つ―{}@{}@{}-" },
          { name: "Serving Dish 3", value: "( ・・)つ-●●●" },
          { name: "Toasting 1", value: "(*´ー`)旦 旦(￣ω￣*)" },
          { name: "Drinking Together", value: "(*´з`)口ﾟ｡ﾟ口(・∀・ )" },
          { name: "Pouring Together", value: "( o^ ^o)且 且(´ω`*)" },
          { name: "Snack & Drink Combo", value: "( ￣▽￣)[] [](≧▽≦ )" },
          { name: "Cheers Duo", value: "( *^^)o∀*∀o(^^* )" },
          { name: "Pour Tea 1", value: "( ^^)_旦~~　 ~~U_(^^ )" },
          { name: "Pour Tea 2", value: "(*￣▽￣)旦 且(´∀`*)" },
          { name: "Drink Line", value: "-●●●-ｃ(・・ )" },
          { name: "Drink Shot", value: "( ・・)つ―●○◎-" },
          { name: "Savoring Drink", value: "(￣﹃￣)" },
          { name: "Happy Drink 1", value: "(๑ᵔ⤙ᵔ๑)" },
          { name: "Happy Drink 2", value: "(´ᵔ⤙ᵔ`)" }
        ],
      },
      {
        subCategory: 'Music',
        description: 'Express your rhythm and love for tunes with our Music kaomojis. This collection is for the music lovers, the dancers, and the shower singers. Featuring characters listening to music, singing, dancing, and playing instruments, these text faces are perfect for sharing a song you love, talking about a concert, or just showing you\'re in a groovy mood. They add a sense of rhythm and melody to your text, helping you share your passion for music in a fun and expressive way. Let the beat drop!',
        kaomojis: [
          { name: 'Listening to Music', value: '🎵( ´θ｀)ノ🎵' },
          { name: 'Singing', value: '(´O｀)' },
          { name: 'Dancing', value: '♪~ ᕕ(ᐛ)ᕗ' },
          { name: 'DJ', value: '🎧' },
          { name: 'Humming', value: '～♪' },
          { name: 'Headphones', value: 'ｄ(￣ ￣)ｂ' },
          { name: 'Grooving', value: 'ヘ( ^o^)ノ＼(^_^ )' },
          { name: 'Rock on', value: ',,/(◣_◢)\\,' },
          { name: 'Playing Guitar', value: '🎸' },
          { name: 'Enjoying Music', value: '(￣▽￣)ノ' },
          { name: "Happy Dance 1", value: "ヾ(´〇`)ﾉ♪♪♪" },
          { name: "Grooving 1", value: "ヘ(￣ω￣ヘ)" },
          { name: "Flowing Dance 1", value: "(〜￣▽￣)〜" },
          { name: "Flowing Dance 2", value: "〜(￣▽￣〜)" },
          { name: "Cheerful Dance 1", value: "ヽ(o´∀`)ﾉ♪♬" },
          { name: "Cheerful Dance 2", value: "(ﾉ≧∀≦)ﾉ" },
          { name: "Joyful Dance 1", value: "♪ヽ(^^ヽ)♪" },
          { name: "Joyful Dance 2", value: "♪(/_ _ )/♪" },
          { name: "Fancy Dance", value: "♪♬((d⌒ω⌒b))♬♪" },
          { name: "Slide Left", value: "└(￣-￣└))" },
          { name: "Slide Right", value: "((┘￣ω￣)┘" },
          { name: "Smooth Step", value: "√(￣‥￣√)" },
          { name: "Two Step Left", value: "└(＾＾)┐" },
          { name: "Two Step Right", value: "┌(＾＾)┘" },
          { name: "Swing Left", value: "＼(￣▽￣)＼" },
          { name: "Swing Right", value: "／(￣▽￣)／" },
          { name: "Musical Step", value: "(￣▽￣)/♫•*¨*•.¸¸♪" },
          { name: "Dance Cheer", value: "(^_^♪)" },
          { name: "Spin Dance 1", value: "(~˘▽˘)~" },
          { name: "Spin Dance 2", value: "~(˘▽˘~)" },
          { name: "Cool Dance", value: "ヾ(⌐■_■)ノ♪" },
          { name: "Relaxed Dance 1", value: "(〜￣△￣)〜" },
          { name: "Relaxed Dance 2", value: "(~‾▽‾)~" },
          { name: "Peaceful Dance", value: "~(˘▽˘)~" },
          { name: "Cute Dance 1", value: "乁( • ω •乁)" },
          { name: "Cute Dance 2", value: "(｢• ω •)｢" },
          { name: "Cute Dance 3", value: "⁽⁽◝( • ω • )◜⁾⁾" },
          { name: "Cute Dance 4", value: "✺◟( • ω • )◞✺" },
          { name: "Music Face", value: "♬♫♪◖(● o ●)◗♪♫♬" },
          { name: "Relaxed Music", value: "( ˘ ɜ˘) ♬♪♫" },
          { name: "Happy Groove", value: "♪♪♪ ヽ(ˇ∀ˇ )ゞ" },
          { name: "Joyful Melody", value: "(ˇ▽ˇ)ノ♪♬♫" }
        ],
      },
      {
        subCategory: 'Games',
        description: 'Level up your conversations with our Gaming kaomojis. This collection is specially designed for the gaming community. You\'ll find text faces representing victory and defeat, intense focus, and the classic NPC stare. They are perfect for reacting during a gaming session, celebrating a win, or complaining about lag. Whether you\'re a console, PC, or mobile gamer, these kaomojis speak your language, adding a fun and relatable layer to your gaming-related chats. Show off your gamer spirit and let your friends know you\'re ready to play.',
        kaomojis: [
          { name: 'Gaming', value: '( ´ ▽ ` )ﾉ 🎮' },
          { name: 'Victory', value: '(^_^)v' },
          { name: 'Game Over', value: '／(^o^)＼' },
          { name: 'Focused', value: '［(－－)］' },
          { name: 'NPC', value: '(´_ゝ｀)' },
          { name: 'Fighting', value: '(ง’̀-‘́)ง' },
          { name: 'Rage Quit', value: '(╯°□°）╯︵ ┻━┻' },
          { name: 'Level Up', value: '☆*:.｡.o(≧▽≦)o.｡.:*☆' },
          { name: 'Defeat', value: '(×_×)' },
          { name: 'Waiting for match', value: '(´-ω-`)' },
          { name: "Ping Pong Rally", value: "( ^^)p_____|_o____q(^^ )" },
          { name: "Tennis Serve", value: "(／o^)/ °⊥ ＼(^o＼)" },
          { name: "Fishing Strike", value: "!(;ﾟoﾟ)o/￣￣￣￣￣￣￣~ >ﾟ))))彡" },
          { name: "Table Flip Fun", value: "ヽ(^o^)ρ┳┻┳°σ(^o^)ノ" },
          { name: "Ball Catch", value: "(／_^)／　　●　＼(^_＼)" },
          { name: "Box vs Box", value: "\"( (≡|≡))_／ ＼_((≡|≡) )\"" },
          { name: "Duel Battle", value: "( ノ-_-)ノﾞ_□ VS □_ヾ(^-^ヽ)" },
          { name: "Exhausted Throw", value: "ヽ(；^ ^)ノﾞ ．．．...___〇" },
          { name: "Tired Strike", value: "(=O*_*)=O Q(*_*Q)" },
          { name: "Gunfire Duel", value: "Ю　○三　＼(￣^￣＼)" },
          { name: "Gaming Fun", value: "(˙ω˙)🎮(˙∀˙)🎮" }
        ],
      },
      {
        subCategory: 'Faces',
        description: 'Explore a diverse range of expressions with our Faces kaomojis. This category is a treasure trove of unique and interesting faces that don\'t neatly fit into other emotional categories. You\'ll find everything from the classic Lenny Face to abstract and artistic creations. This is the place to find a truly unique text face to represent your mood or to use as a signature character. They are perfect for when you want to be a little weird, mysterious, or just stand out from the crowd. Dive in and find a face that\'s as unique as you are.',
        kaomojis: [
          { name: 'Lenny Face', value: '( ͡° ͜ʖ ͡°)' },
          { name: 'Staring', value: '(ಠ_ಠ)' },
          { name: 'Flower Face', value: '（✿・ω・）' },
          { name: 'Look of Disapproval', value: 'ಠ_ಠ' },
          { name: 'Mustache', value: '콧수염' },
          { name: 'Glasses', value: '(⌐■_■)' },
          { name: 'Monocle', value: '(・ω・)ノ' },
          { name: 'Big Eyes', value: '(◎ ◎)ゞ' },
          { name: 'Weird Face', value: '( ° ʖ °)' },
          { name: 'Look at me', value: '(☞ﾟ∀ﾟ)☞' },
          { name: "Classic Lenny", value: "( ͡° ͜ʖ ͡°)" },
          { name: "Sad Lenny", value: "( ͡° ʖ̯ ͡°)" },
          { name: "Shifty Lenny", value: "( ͠° ͟ʖ ͡°)" },
          { name: "Happy Lenny", value: "( ͡ᵔ ͜ʖ ͡ᵔ)" },
          { name: "Pensive Lenny", value: "( . •́ _ʖ •̀ .)" },
          { name: "Angry Lenny", value: "( ఠ ͟ʖ ఠ)" },
          { name: "Frowning Lenny 1", value: "( ͡ಠ ʖ̯ ͡ಠ)" },
          { name: "Frowning Lenny 2", value: "( ಠ ʖ̯ ಠ)" },
          { name: "Mischievous Lenny", value: "( ಠ ͜ʖ ಠ)" },
          { name: "Crying Lenny", value: "( ಥ ʖ̯ ಥ)" },
          { name: "Cute Lenny", value: "( ͡• ͜ʖ ͡• )" },
          { name: "Flirty Lenny", value: "( ･ิ ͜ʖ ･ิ)" },
          { name: "Simple Lenny", value: "( ͡ ͜ʖ ͡ )" },
          { name: "Smug Lenny", value: "(≖ ͜ʖ≖)" },
          { name: "Shocked Lenny 1", value: "(ʘ ʖ̯ ʘ)" },
          { name: "Shocked Lenny 2", value: "(ʘ ͟ʖ ʘ)" },
          { name: "Shocked Lenny 3", value: "(ʘ ͜ʖ ʘ)" },
          { name: "Sad Crying Lenny", value: "(;´༎ຶٹ༎ຶ`)" }
        ],
      },
      {
        subCategory: 'Special',
        description: 'Discover a collection of unique, intricate, and special kaomojis that defy simple categorization. This is where you\'ll find the weird, the wonderful, and the masterfully crafted text faces. From multi-line artistic creations to abstract symbolic representations, these kaomojis are for when you want to make a statement. They are perfect for special occasions, artistic expression, or for when a standard kaomoji just won\'t do. Explore this category to find some of the most creative and impressive examples of kaomoji art.',
        kaomojis: [
          { name: 'Butterfly', value: 'Ƹ̵̡Ӝ̵̨̄Ʒ' },
          { name: 'Sparkles', value: 'キラキラ' },
          { name: 'Menacing', value: 'ゴゴゴゴ' },
          { name: 'Angel', value: '👼( ´ ▽ ` )' },
          { name: 'Devil', value: 'ψ( ` ∇ ´ )ψ' },
          { name: 'King', value: '👑( ´ ▽ ` )' },
          { name: 'Police', value: '＼(・｀(ｪ)・)/' },
          { name: 'Doctor', value: '⚕️' },
          { name: 'Thinking', value: '(´-`).｡oO(🤔)' },
          { name: 'Breaking Down', value: '┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻', isLong: true },
          { name: "Waking Up", value: "٩(ˊ〇ˋ*)و" },
          { name: "Military Salute", value: "(￣^￣)ゞ" },
          { name: "Facepalm", value: "(－‸ლ)" },
          { name: "Table Flip", value: "(╯°益°)╯彡┻━┻" },
          { name: "Mad Table Take", value: "(╮°-°)╮┳━━┳ ( ╯°□°)╯ ┻━━┻" },
          { name: "Putting Table Back", value: "┬─┬ノ( º _ ºノ)" },
          { name: "Surrender", value: "(oT-T)尸" },
          { name: "Lenny Face", value: "( ͡° ͜ʖ ͡°)" },
          { name: "Money", value: "[̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]" },
          { name: "Disapproval Look", value: "(ಠ_ಠ)" },
          { name: "Smoking", value: "౦０o ｡ (‾́。‾́ )y~~" },
          { name: "Zombie Survival", value: "(x(x_(x_x(O_o)x_x)_x)x)" },
          { name: "Pointing", value: "(　･ω･)☞" },
          { name: "Cool with Glasses", value: "(⌐■_■)" },
          { name: "Cute Face", value: "(◕‿◕✿)" },
          { name: "Watching TV", value: "(　￣.)o-　　【　TV　】" },
          { name: "Catching Umbrella", value: "｀、ヽ｀ヽ｀、ヽ(ノ＞＜)ノ ｀、ヽ｀☂ヽ｀、ヽ" },
          { name: "Drowning", value: "‿︵‿︵‿︵‿ヽ(°□° )ノ︵‿︵‿︵‿︵" },
          { name: "Suspicious Gesture", value: "( • )( • )ԅ(≖‿≖ԅ)" },
          { name: "Punishment for Cheating", value: "( ＾▽＾)っ✂╰⋃╯" },
          { name: "Chasing Butterfly", value: "〜〜(／￣▽)／　〜ф" },
          { name: "Angel 1", value: "ଘ(੭ˊᵕˋ)੭* ੈ✩‧₊˚" },
          { name: "Angel 2", value: "ଘ(੭ˊ꒳​ˋ)੭✧" },
          { name: "Lying Emoticon 1", value: "_(:3 」∠)_" },
          { name: "Lying Emoticon 2", value: "∠( ᐛ 」∠)_" }
        ],
      },
    ],
  },
];
