
import type { KaomojiCategory } from '../types';

export const kaomojiData: KaomojiCategory[] = [
  {
    category: '🩷 Emotion',
    kaomojis: [
      { name: 'Happy', value: '(^ω^)' },
      { name: 'Sad', value: '(;´Д｀)' },
      { name: 'Angry', value: '(＃`Д´)' },
      { name: 'Surprised', value: '(o_O)' },
      { name: 'Shy', value: '(⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)' },
      { name: 'Speechless', value: '( speechless... )' },
      { name: 'Worried', value: '(・_・;)' },
      { name: 'Confused', value: '(°_°)' },
      { name: 'Indifferent', value: '( ´-ω-)' },
      { name: 'Excited', value: 'ヽ(・∀・)ﾉ' },
      { name: 'Embarrassed', value: '(⌒_⌒;)' },
      { name: 'Touched', value: '(´感動｀)' },
      { name: 'Disappointed', value: '(´_｀)' },
      { name: 'Helpless', value: '¯\\_(ツ)_/¯' },
      { name: 'Bored', value: '(´-ω-`)' },
      { name: 'Content', value: '(´｡• ᵕ •｡`)' },
      { name: 'Nervous', value: '((´д｀))' },
      { name: 'Jealous', value: '(¬_¬")' },
      { name: 'Frustrated', value: '(-_-)' },
      { name: 'Relieved', value: '(´_ゝ｀)' },
    ]
  },
  {
    category: '💬 Greetings & Interactions',
    kaomojis: [
      { name: 'Hello', value: '( ´ ▽ ` )ﾉ' },
      { name: 'Goodbye', value: '...ε(*´･ω･)ﾉﾞ' },
      { name: 'Good Morning', value: 'おはよう' },
      { name: 'Good Night', value: 'おやすみ' },
      { name: 'Welcome', value: 'おかえり' },
      { name: 'Please', value: '(人◕ω◕)' },
      { name: 'Thank You', value: 'm(_ _)m' },
      { name: 'You\'re Welcome', value: '(´人｀)' },
      { name: 'Sorry', value: 'm(_ _)m' },
      { name: 'Cheer Up', value: 'o(>◡<)o' },
      { name: 'Agree', value: '(*・ω・)(*-ω-)(*・ω・)(*-ω-)' },
      { name: 'Shaking Head', value: '摇头' },
      { name: 'Come Here', value: 'おいで' },
      { name: 'Congratulations', value: '(ﾉ´ヮ´)ﾉ*:･ﾟ✧' },
      { name: 'Blessing', value: '( ´ ∀ ` )ノ～ ♡' },
      { name: 'Happy Birthday', value: '🎂ヽ( ´ ▽ ` )ﾉ' },
      { name: 'Happy Holidays', value: '🎄( ´ ▽ ` )ﾉ' },
      { name: 'Clapping', value: '(´∀｀ﾉﾉ\'ﾟﾁ\'ﾟﾁ)' },
      { name: 'Handshake', value: '( ´∀｀)人(´∀｀ )' },
      { name: 'Waving', value: '( ´ ▽ ` )ﾉ' },
    ]
  },
  {
    category: '🧠 Thinking & Reacting',
    kaomojis: [
      { name: 'Thinking', value: '(・－・)?' },
      { name: 'Don\'t Understand', value: '(´･_･`)' },
      { name: 'Shocked', value: 'Σ(°ロ°)' },
      { name: 'Understood', value: '(´ー｀)' },
      { name: 'Planning', value: '( V)o\o(V )' },
      { name: 'Calculating', value: '[̲̅$̲̅(̲̅ιο̲̅̅)̲̅$̲̅]' },
      { name: 'Hesitating', value: '(´-ι_-｀)' },
      { name: 'Doubting', value: '( →_→)' },
      { name: 'Observing', value: '(◎ ◎)ゞ' },
      { name: 'Analyzing', value: 'φ(．．;)' },
      { name: 'Inspiration', value: '(๑•̀ㅂ•́)و✧' },
      { name: 'Puzzled', value: '(°_°)' },
      { name: 'Remembering', value: 'φ(．．)' },
      { name: 'Pondering', value: '(-_-)' },
      { name: 'Reminiscing', value: '(´-`).｡oO(🤔)' },
      { name: 'Meditating', value: '(´_ゝ｀)' },
      { name: 'Logical', value: '(⌐■_■)' },
      { name: 'Speechless Thinking', value: '(ಠ_ಠ)' },
      { name: 'Procrastinating', value: '明日から本気出す' },
      { name: 'Eureka', value: 'ミ๏ｖ๏彡' },
    ]
  },
  {
    category: '💢 Anger & Displeasure',
    kaomojis: [
      { name: 'Angry', value: '(-`д´-)' },
      { name: 'Venting', value: '( ´Д｀)ﾉ~' },
      { name: 'Annoyed', value: '(￣^￣)' },
      { name: 'Exploding', value: '(☄ฺ◣д◢)☄ฺ' },
      { name: 'Fed Up', value: '(-_-#)' },
      { name: 'Coughing Blood', value: '( 뿜 )' },
      { name: 'Fuming', value: '（-""-；)' },
      { name: 'Table Flip', value: '(╯°□°）╯︵ ┻━┻' },
      { name: 'Breaking Down', value: '┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻' },
      { name: 'Raging', value: 'ヽ( `д´*)ノ' },
      { name: 'Losing Temper', value: '(╬ Ò﹏Ó)' },
      { name: 'Impatient', value: '(>_<)' },
      { name: 'Glaring', value: '( ` ω ´ )' },
      { name: 'Yelling', value: '(((p(>o<)q)))' },
      { name: 'Complaining', value: '( ´-ω-)' },
      { name: 'Provoked', value: '(`⌒´メ)' },
      { name: 'Flipping Off', value: '(凸ಠ益ಠ)凸' },
      { name: 'Throwing Things', value: '(ノಠ益ಠ)ノ彡┻━┻' },
      { name: 'Accusing', value: '(ò_óˇ)' },
      { name: 'Cold Anger', value: '(¬_¬")' },
    ]
  },
  {
    category: '😭 Crying & Emotional Release',
    kaomojis: [
      { name: 'Crying', value: '(´;ω;`)' },
      { name: 'Wailing', value: '｡･ﾟﾟ･(>д<)･ﾟﾟ･｡' },
      { name: 'Crying and Laughing', value: '( ཀ͝ ∧ ཀ͝ )' },
      { name: 'Teary', value: '(ノ_<。)' },
      { name: 'Grieved', value: '(｡•́︿•̀｡)' },
      { name: 'Heartbroken', value: '(´°̥̥̥̥̥̥̥̥ω°̥̥̥̥̥̥̥̥｀)' },
      { name: 'Sinking', value: '... sinking ...' },
      { name: 'Sobbing', value: '(╥_╥)' },
      { name: 'Holding Back Tears', value: '(´-ω-`)' },
      { name: 'Crying from Joy', value: 'o(>< )o' },
      { name: 'Tragedy', value: '(×_×)' },
      { name: 'Crying Out', value: '(＃＞＜)' },
      { name: 'Heartbroken', value: '(╯︵╰,)' },
      { name: 'Watery Eyes', value: '(´;ω;`)' },
      { name: 'Crying Loudly', value: '(T_T)' },
      { name: 'Giving Up', value: '／(^o^)＼' },
      { name: 'Despair', value: '絶望した' },
      { name: 'Breaking Down Crying', value: 'o(>< )o' },
      { name: 'Teary Eyed', value: '(´･_･`)' },
      { name: 'Smiling Through Tears', value: '(´_｀)' },
    ]
  },
  {
    category: '🩵 Love & Romance',
    kaomojis: [
      { name: 'Heart Eyes', value: '(｡♥‿♥｡)' },
      { name: 'Confession', value: '愛してる' },
      { name: 'Kissing', value: '(づ￣ ³￣)づ' },
      { name: 'Hugging', value: '(ɔˆ ³(ˆ⌣ˆc)' },
      { name: 'Pouting', value: '(´,,>ω<,,`)' },
      { name: 'Smitten', value: '(*♡∀♡)' },
      { name: 'Liking', value: '(´,,•ω•,,)♡' },
      { name: 'Doting', value: '(っ´ω`c)' },
      { name: 'Blushing', value: '(//∇//)' },
      { name: 'Thinking of You', value: '(｡･ω･｡)ﾉ♡' },
      { name: 'Sweet', value: '(❤´³`❤)' },
      { name: 'Heartbroken', value: '💔' },
      { name: 'Rejected', value: '(´_｀)' },
      { name: 'Secret Crush', value: '|･ω･｀)' },
      { name: 'First Love', value: '(´⌣`ʃƪ)' },
      { name: 'Crushing', value: '(//∇//)' },
      { name: 'In Love', value: '♡(⇀ 3 ↼)♡' },
      { name: 'Begging', value: '跪いて許しを請う' },
      { name: 'Breaking Up', value: '( ´Д｀)ﾉ~' },
      { name: 'Making Up', value: '(^v^)/' },
    ]
  },
  {
    category: '💀 Negativity & Apathy',
    kaomojis: [
      { name: 'Despair', value: '|(￣3￣)|' },
      { name: 'Giving Up', value: '／(^o^)＼' },
      { name: 'Broken', value: '(×_×)' },
      { name: 'Empty', value: '(´・_・｀)' },
      { name: 'Meaningless', value: '┐(￣ヘ￣)┌' },
      { name: 'Hollow', value: '(´・_・｀)' },
      { name: 'Dejected', value: '(´･_･`)' },
      { name: 'Gloomy', value: '（；＿；）' },
      { name: 'Failure', value: '(´_｀)' },
      { name: 'Lonely', value: '(-_-)' },
      { name: 'Self-deprecating', value: '¯\\_(ツ)_/¯' },
      { name: 'Tired', value: '(－_－) zzZ' },
      { name: 'Shattered', value: '💔' },
      { name: 'Helpless', value: '(´°̥̥̥̥̥̥̥̥ω°̥̥̥̥̥̥̥̥｀)' },
      { name: 'Desolate', value: '(´-ω-`)' },
      { name: 'Zoning Out', value: '(´_ゝ｀)' },
      { name: 'Given Up Hope', value: '絶望した' },
      { name: 'Sinking', value: '... sinking ...' },
      { name: 'Disheartened', value: '(｡•́︿•̀｡)' },
      { name: 'Crying and Laughing', value: '( ཀ͝ ∧ ཀ͝ )' },
    ]
  },
  {
    category: '✨ Happy & Positive',
    kaomojis: [
      { name: 'Happy', value: '(*^▽^*)' },
      { name: 'Laughing Out Loud', value: '(>▽<)' },
      { name: 'Smiling', value: '(´∀｀)' },
      { name: 'Happy Clapping', value: 'o(〃＾▽＾〃)o' },
      { name: 'Excited', value: '☆*:.｡.o(≧▽≦)o.｡.:*☆' },
      { name: 'Satisfied', value: '(⌒‿⌒)' },
      { name: 'Pleased', value: '(^_^)v' },
      { name: 'Tears of Joy', value: '(´感動｀)' },
      { name: 'Relaxed', value: '(￣▽￣)ノ' },
      { name: 'Blissful', value: '(´｡• ᵕ •｡`)' },
      { name: 'Energetic', value: 'o(>ω<)o' },
      { name: 'Dancing', value: 'ヘ( ^o^)ノ＼(^_^ )' },
      { name: 'Grateful', value: '(´人｀)' },
      { name: 'Joyful', value: '＼(￣▽￣)／' },
      { name: 'Surprised', value: '(๑>◡<๑)' },
      { name: 'Feeling Good', value: '(b^ω^)b' },
      { name: 'Full of Energy', value: 'o(>◡<)o' },
      { name: 'Flying with Joy', value: '٩( ᐛ )و' },
      { name: 'Cheering', value: 'ヽ( ´ ▽ ` )ﾉ' },
      { name: 'Optimistic', value: '(๑>◡<๑)' },
    ]
  },
  {
    category: '🐾 Actions',
    kaomojis: [
      { name: 'Dancing', value: '♪~ ᕕ(ᐛ)ᕗ' },
      { name: 'Waving', value: '( ´ ▽ ` )ﾉ' },
      { name: 'Clapping', value: '(´∀｀ﾉﾉ\'ﾟﾁ\'ﾟﾁ)' },
      { name: 'Hugging', value: '(っ´ω`c)' },
      { name: 'Sitting', value: '[_|_]' },
      { name: 'Lying Down', value: '_(」∠ ､ﾝ､)_' },
      { name: 'Kneeling', value: '土下座' },
      { name: 'Fighting', value: '(ง’̀-‘́)ง' },
      { name: 'Saluting', value: '(￣^￣)ゞ' },
      { name: 'Making a Heart', value: '（*’∀’人）♥' },
      { name: 'Pointing', value: '(☞ﾟ∀ﾟ)☞' },
      { name: 'Running Away', value: 'ε=ε=┌( >_<)┘' },
      { name: 'Rolling', value: '둥실둥실' },
      { name: 'Shrugging', value: '¯\\_(ツ)_/¯' },
      { name: 'Raising Hands', value: '(╯✧▽✧)╯' },
      { name: 'Jumping', value: '＼(￣▽￣)／' },
      { name: 'Greeting', value: '( ´ ▽ ` )ﾉ' },
      { name: 'Dozing Off', value: '(－_－) zzZ' },
      { name: 'Winking', value: '(^_-)' },
      { name: 'Nodding', value: '(*・ω・)(*-ω-)(*・ω・)(*-ω-)' },
    ]
  },
  {
    category: '🧍‍♀️ Gestures',
    kaomojis: [
      { name: 'Hands Up', value: 'ヽ(・∀・)ﾉ' },
      { name: 'Palms Together', value: '(´人｀)' },
      { name: 'Hands on Hips', value: '┐(￣ヘ￣)┌' },
      { name: 'Head in Hands', value: '(>_<)' },
      { name: 'Facepalm', value: '(－‸ლ)' },
      { name: 'Facepalm', value: '(－‸ლ)' },
      { name: 'Scratching Head', value: '(・_・ヾ' },
      { name: 'Staring', value: '(o_O)' },
      { name: 'Eyes Closed', value: '(-_-)' },
      { name: 'Mouth Open', value: '(o_O)' },
      { name: 'Tilting Head', value: '(・－・)?' },
      { name: 'Making a Heart', value: '(｡♥‿♥｡)' },
      { name: 'Shrugging', value: '╮( ˘ ､ ˘ )╭' },
      { name: 'Kicking', value: '(ง’̀-‘́)ง' },
      { name: 'Jumping', value: '٩( ᐛ )و' },
      { name: 'Kneeling', value: 'm(_ _)m' },
      { name: 'Hugging Knees', value: '_(」∠ ､ﾝ､)_' },
      { name: 'Hands on Hips', value: '┐(￣ヘ￣)┌' },
      { name: 'Blushing and Covering Mouth', value: '(⁄ ⁄•⁄ω⁄•⁄ ⁄)' },
      { name: 'Winking Smile', value: '(^_-)' },
    ]
  },
  {
    category: '💻 Digital & Online',
    kaomojis: [
      { name: 'Typing Email', value: 'φ(．．;)' },
      { name: 'Typing', value: 'φ(．．;)' },
      { name: 'On Phone', value: '📱(・_・;)' },
      { name: 'Internet Down', value: '(×_×)' },
      { name: 'Lagging', value: '..._.' },
      { name: 'Disconnected', value: 'ε=ε=ε=ε=┌(;￣◇￣)┘' },
      { name: 'Connected', value: '(^_^)v' },
      { name: 'Looking at Screen', value: '［(－－)］' },
      { name: 'Posting', value: 'φ(．．)' },
      { name: 'Replying', value: '( ´-ω-)' },
      { name: 'Downloading', value: '(・_・ヾ' },
      { name: 'Uploading', value: '(・ε・)' },
      { name: 'System Crash', value: '／(^o^)＼' },
      { name: 'Lenny Face', value: '( ͡° ͜ʖ ͡°)' },
      { name: 'Loading', value: '(～￣▽￣)～' },
      { name: 'Using VPN', value: '(⌐■_■)' },
      { name: 'No Internet', value: '(-_-#)' },
      { name: 'Wrong Password', value: '(>_<)' },
      { name: 'Connection Failed', value: 'o(>< )o' },
      { name: 'Hacker Mode', value: '(⌐■_■)' },
    ]
  },
  {
    category: '🐱 Animals',
    kaomojis: [
      { name: 'Cat', value: '(=^･ω･^=)' },
      { name: 'Dog', value: 'V=(° °)=V' },
      { name: 'Bear', value: '(´(エ)｀)' },
      { name: 'Rabbit', value: '（・ｘ・）' },
      { name: 'Bird', value: '（・⊝・）' },
      { name: 'Pig', value: '(´・(oo)・｀)' },
      { name: 'Fox', value: '/(・ x ・)\\' },
      { name: 'Panda', value: '(´･(ｴ)･｀)' },
      { name: 'Tiger', value: '( ` ω ´ )' },
      { name: 'Lion', value: '(◣_◢)o-o-o🦁' },
      { name: 'Sheep', value: '(´｡• ◡ •｡`)' },
      { name: 'Frog', value: '(・o・)' },
      { name: 'Fish', value: '<・)))><<' },
      { name: 'Unicorn', value: '🦄✨(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧' },
      { name: 'Dragon', value: '🐉(-`д´-🐉)' },
      { name: 'Penguin', value: '（・⊝・）' },
      { name: 'Cat Girl', value: '(=^･ω･^=)' },
      { name: 'Dog Person', value: '(´・(oo)・｀)' },
      { name: 'Animal Mix', value: '（＾（´（´・（´・（´・ω・）´・）`）´）＾）' },
      { name: 'Pet Person', value: '@(o･ｪ･o)@' },
    ]
  },
  {
    category: '🍀 Nature & Weather',
    kaomojis: [
      { name: 'Sun', value: '☆*:.｡.o(≧▽≦)o.｡.:*☆' },
      { name: 'Moon', value: '(－_－) zzZ' },
      { name: 'Stars', value: '(★ω★)' },
      { name: 'Cloud', value: '💢☁(＃`Д´)' },
      { name: 'Rain', value: 'ヽ`､ヽ`☂o(･ω･｡)`ヽ､`ヽ､' },
      { name: 'Snow', value: '(ﾉ´ヮ´)ﾉ*:･ﾟ✧' },
      { name: 'Wind', value: '〜(・ω・)〜🎣' },
      { name: 'Thunder', value: '(☄ฺ◣д◢)☄ฺ' },
      { name: 'Flower', value: '🌸(˘⌣˘)🌸' },
      { name: 'Tree', value: '🎄( ´ ▽ ` )ﾉ' },
      { name: 'Grass', value: '(・∀・)🌸' },
      { name: 'Mountain', value: '(´(エ)｀)' },
      { name: 'River', value: '＞°）mニニニニ＝～' },
      { name: 'Wave', value: '＞°）mニニニニ＝～' },
      { name: 'Beach', value: '(´-`).｡oO(🤔)' },
      { name: 'Fire', value: '(☄ฺ◣д◢)☄ฺ' },
      { name: 'Stone', value: '(°_°)' },
      { name: 'Night Sky', value: '☆(・ω・)人(・ω・)☆' },
      { name: 'Rainbow', value: '(ﾉ´ヮ´)ﾉ*:･ﾟ✧' },
      { name: 'Butterfly', value: 'Ƹ̵̡Ӝ̵̨̄Ʒ' },
    ]
  },
  {
    category: '🕹️ Gaming & Entertainment',
    kaomojis: [
      { name: 'Victory', value: '(^_^)v' },
      { name: 'Defeat', value: '(×_×)' },
      { name: 'Level Up', value: '☆*:.｡.o(≧▽≦)o.｡.:*☆' },
      { name: 'Losing HP', value: '(´°̥̥̥̥̥̥̥̥ω°̥̥̥̥̥̥̥̥｀)' },
      { name: 'Fighting', value: '(-_(-_(-_(-_-)_-)-_-)-_-)' },
      { name: 'Game Start', value: 'ヽ(・∀・)ﾉ' },
      { name: 'Game Over', value: '／(^o^)＼' },
      { name: 'Getting Reward', value: '( ´∀｀)っ凵☆凵c(´∀｀ )' },
      { name: 'Battle Stance', value: '(ง’̀-‘́)ง' },
      { name: 'Loot Drop', value: '(💲ω💲)' },
      { name: 'Attacking', value: '(・∀・)・∀・)・∀・)・∀・)・∀・)⌐■-■' },
      { name: 'Defending', value: '(￣^￣)ゞ' },
      { name: 'Equipping', value: '୧༼ಠ益ಠ༽୨' },
      { name: 'Level Up Success', value: 'ヽ( ´ ▽ ` )ﾉ' },
      { name: 'Stealth', value: '┬┴┬┴┤(･_├┬┴┬┴' },
      { name: 'Revived', value: '(´人｀)' },
      { name: 'NPC', value: '(´_ゝ｀)' },
      { name: 'Player Interaction', value: '( ´∀｀)人(´∀｀ )' },
      { name: 'Leaderboard', value: '👑( ´ ▽ ` )' },
      { name: 'Fighting Boss', value: '୧༼ಠ益ಠ༽୨' },
    ]
  },
  {
    category: '🧋 Cute',
    kaomojis: [
      { name: 'Kawaii', value: '(´｡• ◡ •｡`)' },
      { name: 'Small Face', value: '(´• . • `)' },
      { name: 'Pouting', value: '(・ε・)' },
      { name: 'Sticking Tongue Out', value: ':Ｐ' },
      { name: 'Sparkly Eyes', value: '(*^.^*)' },
      { name: 'Dancing Happily', value: 'ヾ(〃^∇^)ﾉ' },
      { name: 'Shy', value: '(⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)' },
      { name: 'Soft and Cute', value: '(´• ω •`)' },
      { name: 'Pitiable', value: '(o´ω`o)' },
      { name: 'Goofy', value: '( ﾟ∀ ﾟ)' },
      { name: 'Mischievous', value: '(^_-)' },
      { name: 'Acting Cute', value: '(｡> ω <｡)' },
      { name: 'Dorky', value: '~(´・ω・`)~' },
      { name: 'Heart Eyes', value: '(♥ω♥*)' },
      { name: 'Little Angel', value: '👼( ´ ▽ ` )' },
      { name: 'Rolling', value: '둥실둥실' },
      { name: 'Giggling', value: '( *´艸`)' },
      { name: 'Sparkles', value: '✨( ´ ▽ ` )✨' },
      { name: 'Starry Eyed', value: '(๑☆‿ ☆#)ᕗ' },
      { name: 'Kiss', value: '(*￣з￣)' },
    ]
  },
  {
    category: '😎 Cool & Confident',
    kaomojis: [
      { name: 'Showing Off', value: '(⌐■_■)' },
      { name: 'Sunglasses', value: '(⌐■_■)' },
      { name: 'Whatever', value: '╮( ˘ ､ ˘ )╭' },
      { name: 'Flexing', value: 'ᕙ(⇀‸↼‶)ᕗ' },
      { name: 'Smug', value: '(^_^)v' },
      { name: 'Mocking', value: '(¬‿¬)' },
      { name: 'Being Cool', value: '( cool )' },
      { name: 'Posing', value: '(✌ﾟ∀ﾟ)☞' },
      { name: 'Cold Smile', value: '( ´-ω-)' },
      { name: 'Elegant', value: '(´_ゝ｀)' },
      { name: 'Shaking Head', value: '摇头' },
      { name: 'Confident Smile', value: '(´_ゝ｀)' },
      { name: 'Arrogant', value: '( ¬_¬)' },
      { name: 'Leisurely', value: '( ´ー｀)y-~~' },
      { name: 'Relaxed', value: '(￣▽￣)ノ' },
      { name: 'Chilling', value: '( ´ー｀)y-~~☕' },
      { name: 'See Through', value: '( ⚭_⚭)' },
      { name: 'Villain Vibe', value: '(ψ▼w▼)ψ' },
      { name: 'King', value: '👑( ´ ▽ ` )' },
      { name: 'Super Confident', value: '\\(★ω★)/' },
    ]
  },
  {
    category: '🤖 Symbolic & Abstract',
    kaomojis: [
      { name: 'Star', value: '(★ω★)' },
      { name: 'Lightning', value: '(☄ฺ◣д◢)☄ฺ' },
      { name: 'Sparks', value: '✨( ´ ▽ ` )✨' },
      { name: 'Wave', value: '＞°）mニニニニ＝～' },
      { name: 'Arrow', value: '(☞ﾟ∀ﾟ)☞' },
      { name: 'Dot Matrix', value: '( ・ω・)' },
      { name: 'Line Face', value: '(-_-)' },
      { name: 'Parentheses', value: '((´д｀))' },
      { name: 'Geometric', value: 'V=(° °)=V' },
      { name: 'ASCII Style', value: '/╲/\\╭(•‿•)╮/\\╱\\' },
      { name: 'Math Symbols', value: '(-_(-_(-_(-_-)_-)-_-)-_-)' },
      { name: 'Mixed Symbols', value: '(ﾉ´ヮ´)ﾉ*:･ﾟ✧' },
      { name: 'Hollow Characters', value: '(o_O)' },
      { name: 'Combined Symbols', value: '( ´∀｀)っ凵☆凵c(´∀｀ )' },
      { name: 'Framed Face', value: '［(－－)］' },
      { name: 'Bracket Style', value: '[_|_]' },
      { name: 'Dot Eyes', value: '(・_・;)' },
      { name: 'Minimalist', value: '(-_-)' },
      { name: 'Mechanical', value: '( ´ ▽ ` )ﾉ 🎮' },
      { name: 'Noise Style', value: '..._.' },
    ]
  },
  {
    category: '🧙 Fantasy & Worldview',
    kaomojis: [
      { name: 'Angel', value: '👼( ´ ▽ ` )' },
      { name: 'Devil', value: 'ψ( ` ∇ ´ )ψ' },
      { name: 'Wizard', value: '(∩^o^)⊃━☆ﾟ.*･｡' },
      { name: 'Fairy', value: 'Ƹ̵̡Ӝ̵̨̄Ʒ' },
      { name: 'Dragon', value: '🐉(-`д´-🐉)' },
      { name: 'Hero', value: '(ง’̀-‘́)ง' },
      { name: 'Witch', value: '୧༼ಠ益ಠ༽୨' },
      { name: 'Prince', value: '( ´ ▽ ` )' },
      { name: 'Princess', value: '👸( ´ ▽ ` )' },
      { name: 'Knight', value: '(￣^￣)ゞ' },
      { name: 'Magic Circle', value: '(∩｀-´)⊃━☆ﾟ.*･｡ﾟ' },
      { name: 'Menacing', value: 'ゴゴゴゴ' },
      { name: 'Summoning', value: '༼ つ ◕_◕ ༽つ' },
      { name: 'Teleporting', value: 'ε=ε=┌( >_<)┘' },
      { name: 'Curse', value: '(凸ಠ益ಠ)凸' },
      { name: 'Mythical', value: '( ´θ｀)ノ' },
      { name: 'Dreaming', value: '(－_－) zzZ' },
      { name: 'Dark Power', value: '((╬◣﹏◢))' },
      { name: 'Light Power', value: '☆*:.｡.o(≧▽≦)o.｡.:*☆' },
      { name: 'Illusion', value: '(@_@)' },
    ]
  },
  {
    category: '🏙️ Daily Life',
    kaomojis: [
      { name: 'Eating', value: '( ´З｀)＝３' },
      { name: 'Sleeping', value: '(ᵕ.ᵕ)' },
      { name: 'Working', value: '💻( ・ω・)´' },
      { name: 'Studying', value: '📖φ(．．;)' },
      { name: 'On Phone', value: '📱(・_・;)' },
      { name: 'Commuting', value: 'C= C= C= ┌(;・ω・)┘' },
      { name: 'Bathing', value: '🚿⊂(´・ω・｀⊂)' },
      { name: 'Shopping', value: '(💲ω💲)' },
      { name: 'Exercising', value: 'ᕙ(⇀‸↼‶)ᕗ' },
      { name: 'Daydreaming', value: '(´-`).｡oO(🤔)' },
      { name: 'On a Date', value: '♡(⇀ 3 ↼)♡' },
      { name: 'Watching Movie', value: '［(－－)］' },
      { name: 'Gaming', value: '( ´ ▽ ` )ﾉ 🎮' },
      { name: 'Housework', value: 'ヽ( ´¬`)ノ' },
      { name: 'Listening to Music', value: '🎵( ´θ｀)ノ🎵' },
      { name: 'Napping', value: '(-ω-ゞ' },
      { name: 'Cooking', value: '(＾ω＾)🔪' },
      { name: 'Going Out', value: 'ε=ε=┌( >_<)┘' },
      { name: 'Coming Home', value: 'おかえり' },
      { name: 'Lying Down', value: '_(」∠ ､ﾝ､)_' },
    ]
  },
  {
    category: '💬 Memes & Reactions',
    kaomojis: [
      { name: 'LOL', value: '(>▽<)' },
      { name: 'Speechless', value: '(ಠ_ಠ)' },
      { name: 'Uhh...', value: '(´･_･`)' },
      { name: 'Oh Boy', value: '(o_O)' },
      { name: 'Crying', value: '(T_T)' },
      { name: 'Can\'t Believe It', value: 'Σ(°ロ°)' },
      { name: 'If You Know You Know', value: '(¬‿¬)' },
      { name: 'So True', value: '( ´_ゝ｀)' },
      { name: 'Triggered', value: '(´°̥̥̥̥̥̥̥̥ω°̥̥̥̥̥̥̥̥｀)' },
      { name: 'So Jealous', value: '(´,,•ω•,,)♡' },
      { name: 'Well...', value: '(・_・;)' },
      { name: 'Confused', value: '(°_°)' },
      { name: 'Epiphany', value: '(๑•̀ㅂ•́)و✧' },
      { name: '???', value: '(・－・)?' },
      { name: 'Lying Down', value: '_(」∠ ､ﾝ､)_' },
      { name: 'We Got This', value: '(^_^)v' },
      { name: 'Amazed', value: 'ミ๏ｖ๏彡' },
      { name: 'Who Gets It', value: '¯\\_(ツ)_/¯' },
      { name: 'I\'m Broken', value: '💔' },
      { name: 'Not Worth Saying', value: '┐(￣ヘ￣)┌' },
    ]
  },
];
