interface Symbol {
  char: string;
  name: string;
}

interface SymbolCategory {
  name: string;
  symbols: Symbol[];
}

export const symbolData: SymbolCategory[] = [
  {
    name: 'Stars & Flowers',
    symbols: [
      { char: '★', name: 'Black Star' },
      { char: '☆', name: 'White Star' },
      { char: '✦', name: 'Black Four-Pointed Star' },
      { char: '✧', name: 'White Four-Pointed Star' },
      { char: '✩', name: 'Stress Outlined White Star' },
      { char: '✪', name: 'Circled White Star' },
      { char: '✫', name: 'Open Center Black Star' },
      { char: '✬', name: 'Black Center White Star' },
      { char: '✭', name: 'Outlined Black Star' },
      { char: '✮', name: 'Heavy Outlined Black Star' },
      { char: '✯', name: 'Pinwheel Star' },
      { char: '✰', name: 'Shadowed White Star' },
      { char: '✶', name: 'Six-Pointed Black Star' },
      { char: '✴', name: 'Eight-Pointed Black Star' },
      { char: '✵', name: 'Eight-Pointed Pinwheel Star' },
      { char: '✷', name: 'Eight-Pointed Rectilinear Black Star' },
      { char: '✸', name: 'Heavy Eight-Pointed Rectilinear Black Star' },
      { char: '✹', name: 'Twelve-Pointed Black Star' },
      { char: '❂', name: 'Circled Open Center Eight-Pointed Star' },
      { char: '✳', name: 'Eight-Spoked Asterisk' },
      { char: '✲', name: 'Open Center Asterisk' },
      { char: '✱', name: 'Heavy Asterisk' },
      { char: '❋', name: 'Heavy Eight-Teardrop-Spoked Propeller Asterisk' },
      { char: '✨', name: 'Sparkles' },
      { char: '❇', name: 'Sparkle' },
      { char: '❈', name: 'Heavy Sparkle' },
      { char: ' உண்டு', name: 'Balloon-Spoked Asterisk' },
      { char: '❊', name: 'Eight-Teardrop-Spoked Propeller Asterisk' },
      { char: '❉', name: 'Heavy-Cheveron Snowflake' },
      { char: '✽', name: 'Heavy Open-Center Eight-Spoked Asterisk' },
      { char: '✾', name: 'Six-Petalled Black and White Florette' },
      { char: '✿', name: 'Black Florette' },
      { char: '❀', name: 'White Florette' },
      { char: '❁', name: 'Eight-Petalled Outlined Black Florette' },
      { char: '❂', name: 'Circled Open Center Eight Pointed Star' },
      { char: '❃', name: 'Heavy Teardrop-Spoked Asterisk' },
      { char: '❄', name: 'Snowflake' },
      { char: '❅', name: 'Tight Trifoliate Snowflake' },
      { char: '❆', name: 'Heavy Chevron Snowflake' },
      { char: ' T ', name: 'Four Teardrop-Spoked Asterisk' },
      { char: '✧', name: 'Four Balloon-Spoked Asterisk' },
      { char: '✥', name: 'Four Club-Spoked Asterisk' },
      { char: '✦', name: 'Black Four Pointed Star' },
    ],
  },
  {
    name: 'Love',
    symbols: [
      { char: '♥', name: 'Black Heart' },
    { char: '♡', name: 'White Heart' },
    { char: '💖', name: 'Sparkling Heart Emoji' },
    { char: '💘', name: 'Heart with Arrow Emoji' },
    { char: '💝', name: 'Heart with Ribbon Emoji' },
    { char: '💗', name: 'Growing Heart Emoji' },
    { char: '💓', name: 'Beating Heart Emoji' },
    { char: '💞', name: 'Revolving Hearts Emoji' },
    { char: '💕', name: 'Two Hearts Emoji' },
    { char: '💌', name: 'Love Letter Emoji' },
    { char: '❣', name: 'Heart Exclamation' },
    { char: '💟', name: 'Heart Decoration Emoji' },
    { char: '💜', name: 'Purple Heart Emoji' },
    { char: '💛', name: 'Yellow Heart Emoji' },
    { char: '💚', name: 'Green Heart Emoji' },
    { char: '🧡', name: 'Orange Heart Emoji' },
    { char: '💙', name: 'Blue Heart Emoji' },
    { char: '💔', name: 'Broken Heart Emoji' },
    { char: '❥', name: 'Rotated Heart' },
    { char: '❦', name: 'Floral Heart' },
    { char: '❧', name: 'Outlined Heart' },
    { char: '❤', name: 'Heavy Black Heart' },
    { char: '🖤', name: 'Black Heart Emoji' },
    { char: '💋', name: 'Kiss Mark Emoji' },
    { char: '😘', name: 'Face Blowing a Kiss Emoji' },
    { char: '😍', name: 'Smiling Face with Heart Eyes Emoji' },
    { char: '🥰', name: 'Smiling Face with Hearts Emoji' },
    { char: '💑', name: 'Couple with Heart Emoji' },
    { char: '💏', name: 'Kissing Couple Emoji' },
    { char: '👩‍❤️‍👨', name: 'Couple with Heart Woman Man Emoji' }
    ]
  },
  {
    name: 'Common Symbols',
    symbols: [
      { char: '©', name: 'Copyright' },
      { char: '®', name: 'Registered Trademark' },
      { char: '™', name: 'Trademark' },
      { char: '℠', name: 'Service Mark' },
      { char: '°', name: 'Degree' },
      { char: '§', name: 'Section' },
      { char: '¶', name: 'Paragraph' },
      { char: '†', name: 'Dagger' },
      { char: '‡', name: 'Double Dagger' },
      { char: '•', name: 'Bullet' },
      { char: '…', name: 'Ellipsis' },
      { char: '‰', name: 'Per Mille' },
      { char: '™', name: 'Trade Mark' },
      { char: '№', name: 'Numero Sign' },
      { char: '℗', name: 'Sound Recording Copyright' },
      { char: '℞', name: 'Prescription Take' },
      { char: 'Ω', name: 'Ohm' },
      { char: '℧', name: 'Inverted Ohm' },
      { char: 'æ', name: 'Latin Small Letter AE' },
      { char: 'Æ', name: 'Latin Capital Letter AE' },
      { char: 'œ', name: 'Latin Small Ligature OE' },
      { char: 'Œ', name: 'Latin Capital Ligature OE' },
      { char: 'þ', name: 'Thorn' },
      { char: 'Þ', name: 'Thorn_' },
      { char: 'ð', name: 'Eth' },
      { char: 'Ð', name: 'Eth_' },
    ],
  },
  {
    name: 'Currency',
    symbols: [
      { char: '$', name: 'Dollar Sign' },
      { char: '¢', name: 'Cent Sign' },
      { char: '£', name: 'Pound Sign' },
      { char: '€', name: 'Euro Sign' },
      { char: '¥', name: 'Yen Sign' },
      { char: '₹', name: 'Indian Rupee Sign' },
      { char: '₽', name: 'Ruble Sign' },
      { char: '₩', name: 'Won Sign' },
      { char: '฿', name: 'Baht Sign' },
      { char: '₫', name: 'Dong Sign' },
      { char: '₭', name: 'Kip Sign' },
      { char: '₮', name: 'Tugrik Sign' },
      { char: '₱', name: 'Peso Sign' },
      { char: '₲', name: 'Guarani Sign' },
      { char: '₴', name: 'Hryvnia Sign' },
      { char: '₵', name: 'Cedi Sign' },
      { char: '₦', name: 'Naira Sign' },
      { char: 'ƒ', name: 'Florin' },
      { char: '₪', name: 'New Shekel Sign' },
      { char: '₼', name: 'Manat Sign' },
      { char: '₺', name: 'Turkish Lira Sign' },
      { char: '₾', name: 'Lari Sign' },
      { char: '₿', name: 'Bitcoin Sign' },
      { char: '₠', name: 'Euro-Currency Sign' },
      { char: '₣', name: 'French Franc Sign' },
      { char: '₤', name: 'Lira Sign' },
      { char: '₧', name: 'Peseta Sign' },
      { char: '¤', name: 'Currency Sign' },
    ],
  },
  {
    name: 'Arrows',
    symbols: [
      { char: '←', name: 'Left Arrow' },
      { char: '↑', name: 'Up Arrow' },
      { char: '→', name: 'Right Arrow' },
      { char: '↓', name: 'Down Arrow' },
      { char: '↔', name: 'Left-Right Arrow' },
      { char: '↕', name: 'Up-Down Arrow' },
      { char: '↖', name: 'North-West Arrow' },
      { char: '↗', name: 'North-East Arrow' },
      { char: '↘', name: 'South-East Arrow' },
      { char: '↙', name: 'South-West Arrow' },
      { char: '↚', name: 'Left Arrow with Stroke' },
      { char: '↛', name: 'Right Arrow with Stroke' },
      { char: '↜', name: 'Left Wave Arrow' },
      { char: '↝', name: 'Right Wave Arrow' },
      { char: '↞', name: 'Left Two-Headed Arrow' },
      { char: '↟', name: 'Up Two-Headed Arrow' },
      { char: '↠', name: 'Right Two-Headed Arrow' },
      { char: '↡', name: 'Down Two-Headed Arrow' },
      { char: '↢', name: 'Left Arrow with Tail' },
      { char: '↣', name: 'Right Arrow with Tail' },
      { char: '↤', name: 'Left Arrow from Bar' },
      { char: '↥', name: 'Up Arrow from Bar' },
      { char: '↦', name: 'Right Arrow from Bar' },
      { char: '↧', name: 'Down Arrow from Bar' },
      { char: '↩', name: 'Left Arrow with Hook' },
      { char: '↪', name: 'Right Arrow with Hook' },
      { char: '↫', name: 'Left Arrow with Loop' },
      { char: '↬', name: 'Right Arrow with Loop' },
      { char: '↭', name: 'Left-Right Wave Arrow' },
      { char: '↮', name: 'Left-Right Arrow with Stroke' },
      { char: '↯', name: 'Down Zigzag Arrow' },
      { char: '↰', name: 'Up Arrow with Tip Left' },
      { char: '↱', name: 'Up Arrow with Tip Right' },
      { char: '↲', name: 'Down Arrow with Tip Left' },
      { char: '↳', name: 'Down Arrow with Tip Right' },
      { char: '↴', name: 'Right Arrow with Corner Down' },
      { char: '↵', name: 'Down Arrow with Corner Left' },
      { char: '↶', name: 'Anticlockwise Top Semicircle Arrow' },
      { char: '↷', name: 'Clockwise Top Semicircle Arrow' },
      { char: '↸', name: 'North-West Arrow to Long Bar' },
      { char: '↹', name: 'Left Arrow to Bar over Right Arrow to Bar' },
      { char: '↺', name: 'Anticlockwise Open Circle Arrow' },
      { char: '↻', name: 'Clockwise Open Circle Arrow' },
      { char: '↼', name: 'Left Harpoon with Barb Up' },
      { char: '↽', name: 'Left Harpoon with Barb Down' },
      { char: '↾', name: 'Up Harpoon with Barb Right' },
      { char: '↿', name: 'Up Harpoon with Barb Left' },
      { char: '⇀', name: 'Right Harpoon with Barb Up' },
      { char: '⇁', name: 'Right Harpoon with Barb Down' },
      { char: '⇂', name: 'Down Harpoon with Barb Right' },
      { char: '⇃', name: 'Down Harpoon with Barb Left' },
      { char: '⇄', name: 'Right Arrow over Left Arrow' },
      { char: '⇅', name: 'Up Arrow Left of Down Arrow' },
      { char: '⇆', name: 'Left Arrow over Right Arrow' },
      { char: '⇇', name: 'Left Paired Arrows' },
      { char: '⇈', name: 'Up Paired Arrows' },
      { char: '⇉', name: 'Right Paired Arrows' },
      { char: '⇊', name: 'Down Paired Arrows' },
      { char: '⇐', name: 'Left Double Arrow' },
      { char: '⇑', name: 'Up Double Arrow' },
      { char: '⇒', name: 'Right Double Arrow' },
      { char: '⇓', name: 'Down Double Arrow' },
      { char: '⇔', name: 'Left-Right Double Arrow' },
      { char: '⇕', name: 'Up-Down Double Arrow' },
      { char: '⇚', name: 'Left Double Arrow with Stroke' },
      { char: '⇛', name: 'Right Double Arrow with Stroke' },
      { char: '⇝', name: 'Right Squiggle Arrow' },
      { char: '⇞', name: 'Up Arrow with Double Stroke' },
      { char: '⇟', name: 'Down Arrow with Double Stroke' },
    ],
  },
  {
    name: 'Math & Logic',
    symbols: [
      { char: '+', name: 'Plus' },
      { char: '-', name: 'Minus' },
      { char: '×', name: 'Multiply' },
      { char: '÷', name: 'Divide' },
      { char: '=', name: 'Equals' },
      { char: '≠', name: 'Not Equal' },
      { char: '<', name: 'Less Than' },
      { char: '>', name: 'Greater Than' },
      { char: '≤', name: 'Less Than or Equal To' },
      { char: '≥', name: 'Greater Than or Equal To' },
      { char: '±', name: 'Plus-Minus' },
      { char: '∓', name: 'Minus-Plus' },
      { char: '√', name: 'Square Root' },
      { char: '∛', name: 'Cube Root' },
      { char: '∜', name: 'Fourth Root' },
      { char: '∞', name: 'Infinity' },
      { char: '∑', name: 'Summation' },
      { char: '∏', name: 'Product' },
      { char: '∫', name: 'Integral' },
      { char: '∬', name: 'Double Integral' },
      { char: '∭', name: 'Triple Integral' },
      { char: '∮', name: 'Contour Integral' },
      { char: '∂', name: 'Partial Differential' },
      { char: '∇', name: 'Nabla' },
      { char: '∆', name: 'Increment / Laplace Operator' },
      { char: '∀', name: 'For All' },
      { char: '∃', name: 'There Exists' },
      { char: '∄', name: 'There Does Not Exist' },
      { char: '∅', name: 'Empty Set' },
      { char: '∈', name: 'Element Of' },
      { char: '∉', name: 'Not an Element Of' },
      { char: '∋', name: 'Contains as Member' },
      { char: '⊂', name: 'Subset Of' },
      { char: '⊃', name: 'Superset Of' },
      { char: '⊆', name: 'Subset of or Equal To' },
      { char: '⊇', name: 'Superset of or Equal To' },
      { char: '∪', name: 'Union' },
      { char: '∩', name: 'Intersection' },
      { char: '∧', name: 'Logical And' },
      { char: '∨', name: 'Logical Or' },
      { char: '¬', name: 'Not' },
      { char: '∴', name: 'Therefore' },
      { char: '∵', name: 'Because' },
      { char: '≈', name: 'Approximately Equal To' },
      { char: '≅', name: 'Congruent To' },
      { char: '≡', name: 'Identical To' },
      { char: '∝', name: 'Proportional To' },
      { char: '⊥', name: 'Perpendicular' },
      { char: '∠', name: 'Angle' },
      { char: 'π', name: 'Pi' },
      { char: '‰', name: 'Per mille' },
      { char: '‱', name: 'Per ten thousand' },
      { char: 'ƒ', name: 'Function' },
      { char: 'ℵ', name: 'Aleph' },
      { char: 'ℶ', name: 'Beth' },
      { char: 'ℷ', name: 'Gimel' },
      { char: 'ℸ', name: 'Daleth' },
      { char: '′', name: 'Prime' },
      { char: '″', name: 'Double Prime' },
      { char: '‴', name: 'Triple Prime' },
      { char: 'ⁿ', name: 'Superscript n' },
    ],
  },
  {
    name: 'Greek Alphabet',
    symbols: [
      { char: 'Α', name: 'Alpha (uppercase)' }, { char: 'α', name: 'alpha (lowercase)' },
      { char: 'Β', name: 'Beta (uppercase)' }, { char: 'β', name: 'beta (lowercase)' },
      { char: 'Γ', name: 'Gamma (uppercase)' }, { char: 'γ', name: 'gamma (lowercase)' },
      { char: 'Δ', name: 'Delta (uppercase)' }, { char: 'δ', name: 'delta (lowercase)' },
      { char: 'Ε', name: 'Epsilon (uppercase)' }, { char: 'ε', name: 'epsilon (lowercase)' },
      { char: 'Ζ', name: 'Zeta (uppercase)' }, { char: 'ζ', name: 'zeta (lowercase)' },
      { char: 'Η', name: 'Eta (uppercase)' }, { char: 'η', name: 'eta (lowercase)' },
      { char: 'Θ', name: 'Theta (uppercase)' }, { char: 'θ', name: 'theta (lowercase)' },
      { char: 'Ι', name: 'Iota (uppercase)' }, { char: 'ι', name: 'iota (lowercase)' },
      { char: 'Κ', name: 'Kappa (uppercase)' }, { char: 'κ', name: 'kappa (lowercase)' },
      { char: 'Λ', name: 'Lambda (uppercase)' }, { char: 'λ', name: 'lambda (lowercase)' },
      { char: 'Μ', name: 'Mu (uppercase)' }, { char: 'μ', name: 'mu (lowercase)' },
      { char: 'Ν', name: 'Nu (uppercase)' }, { char: 'ν', name: 'nu (lowercase)' },
      { char: 'Ξ', name: 'Xi (uppercase)' }, { char: 'ξ', name: 'xi (lowercase)' },
      { char: 'Ο', name: 'Omicron (uppercase)' }, { char: 'ο', name: 'omicron (lowercase)' },
      { char: 'Π', name: 'Pi (uppercase)' }, { char: 'π', name: 'pi (lowercase)' },
      { char: 'Ρ', name: 'Rho (uppercase)' }, { char: 'ρ', name: 'rho (lowercase)' },
      { char: 'Σ', name: 'Sigma (uppercase)' }, { char: 'σ', name: 'sigma (lowercase)' },
      { char: 'Τ', name: 'Tau (uppercase)' }, { char: 'τ', name: 'tau (lowercase)' },
      { char: 'Υ', name: 'Upsilon (uppercase)' }, { char: 'υ', name: 'upsilon (lowercase)' },
      { char: 'Φ', name: 'Phi (uppercase)' }, { char: 'φ', name: 'phi (lowercase)' },
      { char: 'Χ', name: 'Chi (uppercase)' }, { char: 'χ', name: 'chi (lowercase)' },
      { char: 'Ψ', name: 'Psi (uppercase)' }, { char: 'ψ', name: 'psi (lowercase)' },
      { char: 'Ω', name: 'Omega (uppercase)' }, { char: 'ω', name: 'omega (lowercase)' },
    ],
  },
  {
    name: 'Punctuation & Brackets',
    symbols: [
      { char: '·', name: 'Middle Dot' },
      { char: '‘', name: 'Left Single Quotation Mark' },
      { char: '’', name: 'Right Single Quotation Mark' },
      { char: '“', name: 'Left Double Quotation Mark' },
      { char: '”', name: 'Right Double Quotation Mark' },
      { char: '„', name: 'Double Low-9 Quotation Mark' },
      { char: '‚', name: 'Single Low-9 Quotation Mark' },
      { char: '‹', name: 'Single Left-Pointing Angle Quotation Mark' },
      { char: '›', name: 'Single Right-Pointing Angle Quotation Mark' },
      { char: '«', name: 'Left-Pointing Double Angle Quotation Mark' },
      { char: '»', name: 'Right-Pointing Double Angle Quotation Mark' },
      { char: '‐', name: 'Hyphen' },
      { char: '–', name: 'En Dash' },
      { char: '—', name: 'Em Dash' },
      { char: '¡', name: 'Inverted Exclamation Mark' },
      { char: '¿', name: 'Inverted Question Mark' },
      { char: '‽', name: 'Interrobang' },
      { char: '※', name: 'Reference Mark' },
      { char: '´', name: 'Acute Accent' },
      { char: '`', name: 'Grave Accent' },
      { char: '¨', name: 'Diaeresis' },
      { char: 'ˆ', name: 'Circumflex Accent' },
      { char: '˜', name: 'Tilde' },
      { char: '¸', name: 'Cedilla' },
      { char: '¯', name: 'Macron' },
      { char: '˘', name: 'Breve' },
      { char: '˙', name: 'Dot Above' },
      { char: '˚', name: 'Ring Above' },
      { char: '˛', name: 'Ogonek' },
      { char: '˝', name: 'Double Acute Accent' },
      { char: 'ˇ', name: 'Caron' },
      { char: '「', name: 'Left Corner Bracket' },
      { char: '」', name: 'Right Corner Bracket' },
      { char: '『', name: 'Left White Corner Bracket' },
      { char: '』', name: 'Right White Corner Bracket' },
      { char: '【', name: 'Left Black Lenticular Bracket' },
      { char: '】', name: 'Right Black Lenticular Bracket' },
      { char: '〖', name: 'Left Tortoise Shell Bracket' },
      { char: '〗', name: 'Right Tortoise Shell Bracket' },
      { char: '⦅', name: 'Left White Curly Bracket' },
      { char: '⦆', name: 'Right White Curly Bracket' },
      { char: '⦇', name: 'Left White Parenthesis' },
      { char: '⦈', name: 'Right White Parenthesis' },
    ],
  },
  {
    name: 'Checks & Crosses',
    symbols: [
      { char: '✓', name: 'Check Mark' },
      { char: '✔', name: 'Heavy Check Mark' },
      { char: '✗', name: 'Ballot X' },
      { char: '✘', name: 'Heavy Ballot X' },
      { char: '✅', name: 'Check Mark Button' },
      { char: '☑', name: 'Ballot Box with Check' },
      { char: '❎', name: 'Cross Mark Button' },
      { char: '☒', name: 'Ballot Box with X' },
      { char: '✓', name: 'Checkmark' },
      { char: '❌', name: 'Cross Mark' },
    ]
  },
  {
    name: 'Geometric Shapes',
    symbols: [
      { char: '■', name: 'Black Square' },
      { char: '□', name: 'White Square' },
      { char: '▪', name: 'Black Small Square' },
      { char: '▫', name: 'White Small Square' },
      { char: '▲', name: 'Black Up-Pointing Triangle' },
      { char: '△', name: 'White Up-Pointing Triangle' },
      { char: '▼', name: 'Black Down-Pointing Triangle' },
      { char: '▽', name: 'White Down-Pointing Triangle' },
      { char: '◆', name: 'Black Diamond' },
      { char: '◇', name: 'White Diamond' },
      { char: '●', name: 'Black Circle' },
      { char: '○', name: 'White Circle' },
      { char: '◘', name: 'Black Circle with White Star' },
      { char: '◙', name: 'White Circle with Black Star' },
      { char: '◦', name: 'White Bullet' },
      { char: '▬', name: 'Black Rectangle' },
      { char: '▭', name: 'White Rectangle' },
      { char: '▮', name: 'Black Vertical Rectangle' },
      { char: '▯', name: 'White Vertical Rectangle' },
      { char: '▰', name: 'Black Parallelogram' },
      { char: '▱', name: 'White Parallelogram' },
      { char: '◊', name: 'Lozenge' },
      { char: '⬬', name: 'White Hexagon' },
      { char: '⬭', name: 'White Octagon' },
      { char: '⬰', name: 'Black Pentagon' },
      { char: '⬱', name: 'White Pentagon' },
    ],
  },
  {
    name: 'Box Drawing',
    symbols: [
      { char: '─', name: 'Box Drawings Light Horizontal' },
      { char: '│', name: 'Box Drawings Light Vertical' },
      { char: '┌', name: 'Box Drawings Light Down and Right' },
      { char: '┐', name: 'Box Drawings Light Down and Left' },
      { char: '└', name: 'Box Drawings Light Up and Right' },
      { char: '┘', name: 'Box Drawings Light Up and Left' },
      { char: '├', name: 'Box Drawings Light Vertical and Right' },
      { char: '┤', name: 'Box Drawings Light Vertical and Left' },
      { char: '┬', name: 'Box Drawings Light Down and Horizontal' },
      { char: '┴', name: 'Box Drawings Light Up and Horizontal' },
      { char: '┼', name: 'Box Drawings Light Vertical and Horizontal' },
      { char: '═', name: 'Box Drawings Double Horizontal' },
      { char: '║', name: 'Box Drawings Double Vertical' },
      { char: '╒', name: 'Box Drawings Down Single and Right Double' },
      { char: '╓', name: 'Box Drawings Down Double and Right Single' },
      { char: '╔', name: 'Box Drawings Double Down and Right' },
      { char: '╕', name: 'Box Drawings Down Single and Left Double' },
      { char: '╖', name: 'Box Drawings Down Double and Left Single' },
      { char: '╗', name: 'Box Drawings Double Down and Left' },
      { char: '╘', name: 'Box Drawings Up Single and Right Double' },
      { char: '╙', name: 'Box Drawings Up Double and Right Single' },
      { char: '╚', name: 'Box Drawings Double Up and Right' },
      { char: '╛', name: 'Box Drawings Up Single and Left Double' },
      { char: '╜', name: 'Box Drawings Up Double and Left Single' },
      { char: '╝', name: 'Box Drawings Double Up and Left' },
      { char: '╞', name: 'Box Drawings Vertical Single and Right Double' },
      { char: '╟', name: 'Box Drawings Vertical Double and Right Single' },
      { char: '╠', name: 'Box Drawings Double Vertical and Right' },
      { char: '╡', name: 'Box Drawings Vertical Single and Left Double' },
      { char: '╢', name: 'Box Drawings Vertical Double and Left Single' },
      { char: '╣', name: 'Box Drawings Double Vertical and Left' },
      { char: '╤', name: 'Box Drawings Down Single and Horizontal Double' },
      { char: '╥', name: 'Box Drawings Down Double and Horizontal Single' },
      { char: '╦', name: 'Box Drawings Double Down and Horizontal' },
      { char: '╧', name: 'Box Drawings Up Single and Horizontal Double' },
      { char: '╨', name: 'Box Drawings Up Double and Horizontal Single' },
      { char: '╩', name: 'Box Drawings Double Up and Horizontal' },
      { char: '╪', name: 'Box Drawings Vertical Single and Horizontal Double' },
      { char: '╫', name: 'Box Drawings Vertical Double and Horizontal Single' },
      { char: '╬', name: 'Box Drawings Double Vertical and Horizontal' },
    ],
  },
  {
    name: 'Block Elements',
    symbols: [
      { char: '▀', name: 'Upper Half Block' },
      { char: '▄', name: 'Lower Half Block' },
      { char: '█', name: 'Full Block' },
      { char: '▌', name: 'Left Half Block' },
      { char: '▐', name: 'Right Half Block' },
      { char: '░', name: 'Light Shade' },
      { char: '▒', name: 'Medium Shade' },
      { char: '▓', name: 'Dark Shade' },
    ],
  },
  {
    name: 'Miscellaneous',
    symbols: [
      { char: '♀', name: 'Female Sign' },
      { char: '♂', name: 'Male Sign' },
      { char: '⚥', name: 'Male and Female Sign' },
      { char: '⚢', name: 'Doubled Female Sign' },
      { char: '⚣', name: 'Doubled Male Sign' },
      { char: '⚤', name: 'Interlocked Female and Male Sign' },
      { char: '⚦', name: 'Male with Stroke Sign' },
      { char: '⚧', name: 'Transgender Symbol' },
      { char: '☿', name: 'Mercury' },
      { char: '♁', name: 'Earth' },
      { char: '⚬', name: 'Medium Small White Circle' },
      { char: '⚭', name: 'Marriage Symbol' },
      { char: '⚮', name: 'Divorce Symbol' },
      { char: '⚯', name: 'Unmarried Partnership Symbol' },
      { char: '☨', name: 'Cross of Lorraine' },
      { char: '☦', name: 'Orthodox Cross' },
      { char: '☧', name: 'Chi Rho' },
      { char: '☮', name: 'Peace Symbol' },
      { char: '☯', name: 'Yin Yang' },
      { char: '☹', name: 'Frowning Face' },
      { char: '☺', name: 'Smiling Face' },
      { char: '☻', name: 'Black Smiling Face' },
      { char: '☼', name: 'White Sun with Rays' },
      { char: '☀', name: 'Sun' },
      { char: '☁', name: 'Cloud' },
      { char: '☂', name: 'Umbrella' },
      { char: '☃', name: 'Snowman' },
      { char: '☄', name: 'Comet' },
      { char: '♠', name: 'Spade Suit' },
      { char: '♣', name: 'Club Suit' },
      { char: '♥', name: 'Heart Suit' },
      { char: '♦', name: 'Diamond Suit' },
      { char: '♪', name: 'Eighth Note' },
      { char: '♫', name: 'Beamed Eighth Notes' },
      { char: '♩', name: 'Quarter Note' },
      { char: '♬', name: 'Beamed Sixteenth Notes' },
      { char: '♭', name: 'Flat' },
      { char: '♮', name: 'Natural' },
      { char: '♯', name: 'Sharp' },
      { char: '♲', name: 'Recycling Symbol for Generic Materials' },
      { char: '♻', name: 'Recycling Symbol' },
      { char: '♳', name: 'Recycling Symbol for Type-1 Plastics' },
      { char: '♴', name: 'Recycling Symbol for Type-2 Plastics' },
      { char: '♵', name: 'Recycling Symbol for Type-3 Plastics' },
      { char: '♶', name: 'Recycling Symbol for Type-4 Plastics' },
      { char: '♷', name: 'Recycling Symbol for Type-5 Plastics' },
      { char: '♸', name: 'Recycling Symbol for Type-6 Plastics' },
      { char: '♹', name: 'Recycling Symbol for Type-7 Plastics' },
      { char: '♺', name: 'Recycling Symbol for Paper' },
      { char: '♾', name: 'Infinity' },
    ],
  },
];
